#!/bin/bash -eu
. "11-rtbh-local/$(basename "$0")"
cat <<EOS
router bgp ${AS}
 address-family ipv4
  neighbor ${ISP_REMOTE_V6} send-community
 exit-address-family
 !
 address-family ipv6
  neighbor ${ISP_REMOTE_V4} send-community
 exit-address-family
!
ip community-list standard RTBH permit 65535:666
!
route-map Transit-out permit 5
 match community aggregate customer-pi RTBH
!
EOS
return 2>/dev/null || echo "end"
