#!/bin/bash -eu
. l2-3-stp/gen-edgeX

conf_vlans_edge_vlan () {
  cat <<END
!
vtp mode off
!
vlan ${BUILDING}0
 name MGMT${BUILDING}
vlan ${BUILDING}1
 name STAFF${BUILDING}
vlan ${BUILDING}2
 name STUDENT${BUILDING}
END
}
render_vlans=conf_vlans_edge_vlan

conf_interfaces_edge_vlan () {
  trunk GigabitEthernet0/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to dist1-b${BUILDING}.campus${CAMPUS}"
  case ${DEV} in
  1) trunk GigabitEthernet0/1 ${BUILDING}0-${BUILDING}2 "Trunk Link to dist1-b${BUILDING}.campus${CAMPUS}"
  ;;
  esac
  cat <<END
!
interface range GigabitEthernet1/0 - 3
 description Access Port VLAN ${BUILDING}1 STAFF
 switchport mode access
 switchport access vlan ${BUILDING}1
 load-interval 30
 no shutdown
!
interface range GigabitEthernet2/0 - 3
 description Access Port VLAN ${BUILDING}2 STUDENT
 switchport mode access
 switchport access vlan ${BUILDING}2
 load-interval 30
 no shutdown
!
interface Vlan 1
 shutdown
!
interface Vlan${BUILDING}0
 description Management VLAN Building ${BUILDING}
 ip address ${IPV4_ADDRESS} 255.255.255.0
 load-interval 30
 ipv6 address ${IPV6_ADDRESS}/64
 no shutdown
END
}
render_interfaces=conf_interfaces_edge_vlan

return 2>/dev/null || render_routed "$@"
