#!/bin/bash -eu
. l2-3-stp/gen-coreX

conf_vlans_core_vlan () {
  cat <<END
!
vtp mode off
!
vlan 10
 name MGMT1
vlan 11
 name STAFF1
vlan 12
 name STUDENT1
vlan 20
 name MGMT2
vlan 21
 name STAFF2
vlan 22
 name STUDENT2
END
}
render_vlans=conf_vlans_core_vlan

conf_stp_core_vlan () {
  cat <<END
!
spanning-tree vlan 10 priority ${PRIORITY}
spanning-tree vlan 11 priority ${PRIORITY}
spanning-tree vlan 12 priority ${PRIORITY}
spanning-tree vlan 20 priority ${PRIORITY}
spanning-tree vlan 21 priority ${PRIORITY}
spanning-tree vlan 22 priority ${PRIORITY}
END
}
render_stp=conf_stp_core_vlan

conf_stp_interfaces_vlan () {
  trunk GigabitEthernet0/1 1,2,10-12,1002-1005 "Trunk Link to dist1-b1.campus${CAMPUS}"
  trunk GigabitEthernet0/2 1,2,20-22,1002-1005 "Trunk Link to dist1-b2.campus${CAMPUS}"
  cat <<END
!
interface Vlan1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 no shutdown
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 no shutdown
END
}
render_interfaces=conf_stp_interfaces_vlan

return 2>/dev/null || render "$@"
