#!/bin/bash -eu
. l2-3-stp/gen-distX

conf_vlans_dist_vlan () {
  cat <<END
!
vtp mode off
!
vlan ${BUILDING}0
 name MGMT${BUILDING}
vlan ${BUILDING}1
 name STAFF${BUILDING}
vlan ${BUILDING}2
 name STUDENT${BUILDING}
END
}
render_vlans=conf_vlans_dist_vlan

conf_interfaces_dist_vlan () {
 trunk GigabitEthernet0/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to core1.campus${CAMPUS}"
 trunk GigabitEthernet1/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}"
 trunk GigabitEthernet1/1 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}"
 trunk GigabitEthernet2/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge2-b${BUILDING}.campus${CAMPUS}"
  cat <<END
!
interface Vlan 1
 shutdown
!
interface Vlan${BUILDING}0
 description Management VLAN Building ${BUILDING}
 ip address ${IPV4_ADDRESS} 255.255.255.0
 load-interval 30
 ipv6 address ${IPV6_ADDRESS}/64
 no shutdown
END
}
render_interfaces=conf_interfaces_dist_vlan

return 2>/dev/null || render_routed "$@"
