#!/bin/bash -eu
. l2-4-vlan/gen-distX

conf_interfaces_dist_l2final () {
  trunk Port-channel1 ${BUILDING}0-${BUILDING}2 "Aggregate Link to edge1-b${BUILDING}.campus${CAMPUS}"
  trunk GigabitEthernet0/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to core1.campus${CAMPUS}"
  trunk GigabitEthernet1/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}"
  echo " channel-group 1 mode active"
  trunk GigabitEthernet1/1 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}"
  echo " channel-group 1 mode active"
  trunk GigabitEthernet2/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge2-b${BUILDING}.campus${CAMPUS}"
  cat <<END
!
interface Vlan 1
 shutdown
!
interface Vlan${BUILDING}0
 description Management VLAN Building ${BUILDING}
 ip address ${IPV4_ADDRESS} 255.255.255.0
 load-interval 30
 ipv6 address ${IPV6_ADDRESS}/64
 no shutdown
END
}
render_interfaces=conf_interfaces_dist_l2final

return 2>/dev/null || render_routed "$@"  
