#!/bin/bash -eu
. l2-4-vlan/gen-edgeX

conf_stp_edge_l2final () {
cat <<END
!
ip dhcp snooping vlan ${BUILDING}1-${BUILDING}2
ip dhcp snooping
!
spanning-tree mode mst
spanning-tree portfast edge bpduguard default
spanning-tree mst 0 priority ${PRIORITY}
END
}
render_stp=conf_stp_edge_l2final

conf_interfaces_edge_l2final() {
  case ${DEV} in
  1) trunk Port-channel1 ${BUILDING}0-${BUILDING}2 "Aggregate Link to dist1-b${BUILDING}.campus${CAMPUS}"
     echo " ip dhcp snooping trust"
     trunk GigabitEthernet0/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to dist1-b${BUILDING}.campus${CAMPUS}"
     echo " channel-group 1 mode active"
     trunk GigabitEthernet0/1 ${BUILDING}0-${BUILDING}2 "Trunk Link to dist1-b${BUILDING}.campus${CAMPUS}"
     echo " channel-group 1 mode active"
  ;;
  2) trunk GigabitEthernet0/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to dist1-b${BUILDING}.campus${CAMPUS}"
     echo " ip dhcp snooping trust"
  ;;
  esac
  cat <<END
!
interface range GigabitEthernet1/0 - 3
 description Access Port VLAN ${BUILDING}1 STAFF
 switchport mode access
 switchport access vlan ${BUILDING}1
 spanning-tree portfast
 load-interval 30
 no shutdown
!
interface range GigabitEthernet2/0 - 3
 description Access Port VLAN ${BUILDING}2 STUDENT
 switchport mode access
 switchport access vlan ${BUILDING}2
 spanning-tree portfast
 load-interval 30
 no shutdown
!
interface Vlan 1
 shutdown
!
interface Vlan${BUILDING}0
 description Management VLAN Building ${BUILDING}
 ip address ${IPV4_ADDRESS} 255.255.255.0
 load-interval 30
 ipv6 address ${IPV6_ADDRESS}/64
 no shutdown
END
}
render_interfaces=conf_interfaces_edge_l2final

return 2>/dev/null || render_routed "$@"
