#!/bin/bash -eu
. l2-4-vlan/gen-distX

conf_interfaces_dist_l2final () {
  cat <<END
!
interface Vlan 1
 shutdown
!
interface Vlan${BUILDING}0
 description Management VLAN Building ${BUILDING}
 ip address ${IPV4_ADDRESS} 255.255.255.0
 ipv6 address ${IPV6_ADDRESS}/64
 load-interval 30
 no shut
!
interface Port-channel1
 description LAG to Edge Switch 1
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shut
!
interface GigabitEthernet0/0
 description Trunk Link to core1.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shut
!
interface GigabitEthernet1/0
 description Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 channel-group 1 mode on
 load-interval 30
 no shut
!
interface GigabitEthernet1/1
 description Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 channel-group 1 mode on
 load-interval 30
 no shut
!
interface GigabitEthernet2/0
 description Trunk Link to edge2-b${BUILDING}.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shut
END
}
render_interfaces=conf_interfaces_dist_l2final

return 2>/dev/null || render_routed "$@"  
