#!/bin/bash -eu
CAMPUS=$2

. address-mappings

NREN_V4_HOST="$((4 * ${CAMPUS} - 2))"

cat <<EOM
hostname bdr1.campus${CAMPUS}
!
aaa new-model
aaa authentication login default local
aaa authentication enable default enable
!
no logging console
logging buffered 8192 debugging
ipv6 unicast-routing
ipv6 cef
no ip domain-lookup
ip domain name ws.nsrc.org
!
username cndlab secret lab-PW
enable secret lab-EN
service password-encryption
!
interface GigabitEthernet0/0
 description Link to NREN
 ip address ${NREN_V4_SUBNET}.${NREN_V4_HOST} 255.255.255.252
 ipv6 address ${NREN_V6_SUBNET}:${CAMPUS}::1/127
 load-interval 30
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
interface GigabitEthernet0/1
 description Link to CAMPUS CORE
 ip address ${CAMPUS_CORE_V4_SUBNET}.1 255.255.255.240
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::1/64
 load-interval 30
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
ip route 0.0.0.0 0.0.0.0 ${NREN_V4_SUBNET}.$((${NREN_V4_HOST} - 1))
ipv6 route ::/0 ${NREN_V6_SUBNET}:${CAMPUS}::0
!
ip route ${CAMPUS_SRVR_V4_SUBNET}.128 255.255.255.240 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD1_V4_MGMT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD2_V4_MGMT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD1_V4_STAFF_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD2_V4_STAFF_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
!
ipv6 route ${CAMPUS_SRVR_V6_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD1_V6_MGMT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD2_V6_MGMT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD1_V6_STAFF_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD2_V6_STAFF_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
!
line con 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line aux 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line vty 0 4
 exec-timeout 0 0
 transport preferred none
!
end
EOM
