#!/bin/bash -eu
. common-P
preamble_iosv
cat <<EOS
interface Loopback0
 description Loopback on P${GROUP}
 ip address 100.68.${GROUP}.3 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::3/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.19 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ip router isis as${AS}
 ipv6 address 2001:DB8:${GROUP}:11::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
!
interface GigabitEthernet0/2
 description Link to Group ${PEER_GROUP} Peering Router
 ip address ${PEER_LOCAL_V4} 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ipv6 address ${PEER_LOCAL_V6}/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet0/3
 description AS${AS} link to IXP
 ip address 100.127.1.${GROUP} 255.255.255.0
 no ip redirects
 no ip proxy-arp
 ipv6 address 2001:DB8:FFFF:1::${GROUP}/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
router isis as${AS}
 net 49.0001.000${GROUP}.0003.00
 is-type level-2-only
 authentication mode md5 level-2
 authentication key-chain as${AS}-key level-2
 metric-style wide
 set-overload-bit on-startup wait-for-bgp
 log-adjacency-changes all
 metric 100000
 passive-interface GigabitEthernet0/3
 passive-interface Loopback0
 !
 address-family ipv6
  multi-topology
  set-overload-bit on-startup wait-for-bgp
  metric 100000
 exit-address-family
!
router bgp ${AS}
 no bgp enforce-first-as
 bgp log-neighbor-changes
 bgp deterministic-med
 no bgp default ipv4-unicast
 neighbor ibgp-rr peer-group
 neighbor ibgp-rr remote-as ${AS}
 neighbor ibgp-rr description iBGP with RR
 neighbor ibgp-rr password 7 01312134570A04
 neighbor ibgp-rr update-source Loopback0
 neighbor ibgpv6-rr peer-group
 neighbor ibgpv6-rr remote-as ${AS}
 neighbor ibgpv6-rr description iBGP with RR
 neighbor ibgpv6-rr password 7 04792C3603204E
 neighbor ibgpv6-rr update-source Loopback0
 neighbor 2001:DB8:${GROUP}::2 peer-group ibgpv6-rr
 neighbor 2001:DB8:${GROUP}::2 description iBGP with Core
 neighbor ${PEER_REMOTE_V6} remote-as ${PEER_AS}
 neighbor ${PEER_REMOTE_V6} description eBGP with AS${PEER_AS}
 neighbor ${PEER_REMOTE_V6} password 7 1435353B000528
 neighbor 2001:DB8:FFFF:1::FE remote-as 65534
 neighbor 2001:DB8:FFFF:1::FE description eBGP with IXP RS
 neighbor 2001:DB8:FFFF:1::FE password 7 0452131642335F
 neighbor 100.68.${GROUP}.2 peer-group ibgp-rr
 neighbor 100.68.${GROUP}.2 description iBGP with Core
 neighbor ${PEER_REMOTE_V4} remote-as ${PEER_AS}
 neighbor ${PEER_REMOTE_V4} description eBGP with AS${PEER_AS}
 neighbor ${PEER_REMOTE_V4} password 7 1435353B000528
 neighbor 100.127.1.254 remote-as 65534
 neighbor 100.127.1.254 description eBGP with IXP RS
 neighbor 100.127.1.254 password 7 0452131642335F
 !
 address-family ipv4
  neighbor ibgp-rr send-community
  neighbor ibgp-rr next-hop-self
  neighbor 100.68.${GROUP}.2 activate
  neighbor ${PEER_REMOTE_V4} activate
  neighbor ${PEER_REMOTE_V4} prefix-list AS${PEER_AS}-block in
  neighbor ${PEER_REMOTE_V4} prefix-list AS${AS}-block out
  neighbor ${PEER_REMOTE_V4} route-map private-peer-in in
  neighbor 100.127.1.254 activate
  neighbor 100.127.1.254 prefix-list IXP-RS in
  neighbor 100.127.1.254 prefix-list AS${AS}-block out
  neighbor 100.127.1.254 route-map IXP-RS-in in
  distance bgp 200 200 200
 exit-address-family
 !
 address-family ipv6
  distance bgp 200 200 200
  neighbor ibgpv6-rr send-community
  neighbor ibgpv6-rr next-hop-self
  neighbor 2001:DB8:${GROUP}::2 activate
  neighbor ${PEER_REMOTE_V6} activate
  neighbor ${PEER_REMOTE_V6} prefix-list AS${PEER_AS}-v6block in
  neighbor ${PEER_REMOTE_V6} prefix-list AS${AS}-v6block out
  neighbor ${PEER_REMOTE_V6} route-map private-peer-in in
  neighbor 2001:DB8:FFFF:1::FE activate
  neighbor 2001:DB8:FFFF:1::FE prefix-list IXP-v6RS in
  neighbor 2001:DB8:FFFF:1::FE prefix-list AS${AS}-v6block out
  neighbor 2001:DB8:FFFF:1::FE route-map IXP-RS-in in
 exit-address-family
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
ip route 0.0.0.0 0.0.0.0 Null0
!
!
ip prefix-list AS${AS}-block permit 100.68.${GROUP}.0/24
!
ip prefix-list AS${PEER_AS}-block permit 100.68.${PEER_GROUP}.0/24
!
ip prefix-list IXP-RS description IPv4 prefixes from RouteServer
EOS
for G in $(seq "$NGROUPS"); do
  [ "$G" -ne "$GROUP" ] && cat <<EOS
ip prefix-list IXP-RS permit 100.68.${G}.0/24
EOS
done
cat <<EOS
ip prefix-list IXP-RS permit 100.127.0.0/24
ipv6 route ::/0 Null0
ipv6 ioam timestamp
!
!
ipv6 prefix-list AS${AS}-v6block permit 2001:DB8:${GROUP}::/48
!
ipv6 prefix-list AS${PEER_AS}-v6block permit 2001:DB8:${PEER_GROUP}::/48
!
ipv6 prefix-list IXP-v6RS description IPv6 prefixes from RouteServer
EOS
for G in $(seq "$NGROUPS"); do
  [ "$G" -ne "$GROUP" ] && cat <<EOS
ipv6 prefix-list IXP-v6RS permit 2001:DB8:${G}::/48
EOS
done
cat <<EOS
ipv6 prefix-list IXP-v6RS permit 2001:DB8:FFFF::/48
route-map private-peer-in permit 5
 description Local pref for Private Peer
 set local-preference 200
!
route-map IXP-RS-in permit 5
 description Local pref for IXP RS Peers
 set local-preference 150
!
EOS
postamble_iosv
