#!/bin/bash -eu
. l3-5-filter/gen-bdrX

conf_snmp_bdr_nms () {
  cat <<END
!
access-list 99 permit ${CAMPUS_CORE_V4_SUBNET}.128 0.0.0.15
access-list 99 permit ${WS_V4_SUBNET}.0 0.0.0.255
!
snmp-server community ${SNMP_COMMUNITY} RO 99
snmp-server ifindex persist
END
}
render_snmp=conf_snmp_bdr_nms

return 2>/dev/null || render "$@"
