#!/bin/bash -eu
. l2-1-base/gen-edgeX

conf_interfaces_edge_l2ip () {
  cat <<END
!
interface Vlan 1
 ip address $IPV4_ADDRESS 255.255.0.0
 load-interval 30
 ipv6 address $IPV6_ADDRESS/64
 no shutdown
END
}
render_interfaces=conf_interfaces_edge_l2ip

return 2>/dev/null || render_flat "$@"
