#!/bin/bash -eu
. l2-1-base/gen-distX

conf_interfaces_dist_l2ip () {
  cat <<END
!
interface Vlan 1
 ip address ${IPV4_ADDRESS} 255.255.0.0
 ipv6 address ${IPV6_ADDRESS}/64
 load-interval 30
 no shut
END
}
render_interfaces=conf_interfaces_dist_l2ip

return 2>/dev/null || render_flat "$@"
