site_name: NSRC GNS3 Training Platform
theme: readthedocs
repo_url: https://github.com/nsrc-org/nsrc-gns3

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition

nav:
  - 'Introduction': 'index.md'
  - 'Hardware': 'hardware/index.md'
  - 'Software': 'software/index.md'
  - 'OS Installation': 'os-installation/index.md'
  - 'OS Configuration': 'os-configuration/index.md'
  - 'Networking': 'networking/index.md'
  - 'Host Tools': 'host-tools/index.md'
  - 'GNS3 Server': 'gns3-server/index.md'
  - 'GNS3 Client': 'gns3-client/index.md'
  - 'Lab Topologies':
      'Overview': 'topology/overview/index.md'
      'NOC': 'topology/noc/index.md'
      'CNDO': 'topology/cndo/index.md'
      'NMM': 'topology/nmm/index.md'
  - 'Console access': 'console/index.md'
  - 'GNS3 Management': 'management/index.md'
  - 'Classroom Tools': 'classroom-tools/index.md'
  - 'Technical Background': 'technical-background/index.md'
  - 'Unusual Configurations': 'unusual-configurations/index.md'
