site_name: NSRC GNS3 Training Platform
theme: readthedocs
repo_url: https://github.com/nsrc-org/nsrc-gns3

nav:
  - 'Introduction': 'index.md'
  - 'Hardware': 'hardware.md'
  - 'OS Installation': 'os-installation.md'
  - 'OS Configuration': 'os-configuration.md'
  - 'Networking': 'networking.md'
  - 'Host Tools': 'host-tools/index.md'
  - 'GNS3 Server': 'gns3-server.md'
  - 'GNS3 Client': 'gns3-client/index.md'
  - 'Lab Topologies':
      'Overview': 'topology/index.md'
      'NOC': 'topology/noc/index.md'
      'CNDO': 'topology/cndo/index.md'
      'NMM': 'topology/nmm/index.md'
  - 'Console access': 'console/index.md'
