#!/bin/bash -eu
. l3-1-base/gen-bdrX

conf_interfaces_bdr_ip () {
  cat <<END
!
interface GigabitEthernet0/0
 description Link to NREN
 ip address ${NREN_V4_SUBNET}.${NREN_V4_HOST} 255.255.255.252
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${NREN_V6_SUBNET}:${CAMPUS}::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
interface GigabitEthernet0/1
 description Link to CAMPUS CORE
 ip address ${CAMPUS_CORE_V4_SUBNET}.1 255.255.255.240
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::1/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
END
}
render_interfaces=conf_interfaces_bdr_ip

conf_static_bdr_ip () {
  cat <<END
!
ip route 0.0.0.0 0.0.0.0 ${NREN_V4_SUBNET}.$((${NREN_V4_HOST} - 1))
ip route ${CAMPUS_SRVR_V4_SUBNET}.128 255.255.255.240 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD1_V4_MGMT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD2_V4_MGMT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD1_V4_STAFF_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD2_V4_STAFF_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
ip route ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.0 255.255.255.0 ${CAMPUS_CORE_V4_SUBNET}.2
!
ipv6 route ::/0 ${NREN_V6_SUBNET}:${CAMPUS}::0
ipv6 route ${CAMPUS_SRVR_V6_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD1_V6_MGMT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD2_V6_MGMT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD1_V6_STAFF_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD2_V6_STAFF_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
ipv6 route ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::/64 ${CAMPUS_CORE_V6_SUBNET}::2
END
}
render_static=conf_static_bdr_ip

return 2>/dev/null || render "$@"
