#!/bin/bash -eu
. l3-5-filter/gen-bdrX

conf_interfaces_bdr_bgp () {
  cat <<END
!
interface Loopback0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.241 255.255.255.255
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::241/128
 no shutdown
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/0
 description Link to transit1.nren
 ip address ${NREN_V4_SUBNET}.${NREN_V4_HOST} 255.255.255.252
 ip access-group from-nren in
 ip access-group to-nren out
 ip nat outside
 load-interval 30
 ipv6 address ${NREN_V6_SUBNET}:${CAMPUS}::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 traffic-filter from-nren-v6 in
 ipv6 traffic-filter to-nren-v6 out
 no shutdown
!
interface GigabitEthernet0/1
 description Link to CAMPUS CORE
 ip address ${CAMPUS_CORE_V4_SUBNET}.1 255.255.255.240
 ip nat inside
 ip router isis campus${CAMPUS}
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::1/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis campus${CAMPUS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
 no shutdown
!
interface GigabitEthernet0/2
 description Link to transit2.nren
 ip address ${NREN_V4_SUBNET}.$((NREN_V4_HOST + 128)) 255.255.255.252
 ip access-group from-nren in
 ip access-group to-nren out
 ip nat outside
 load-interval 30
 ipv6 address ${NREN_V6_SUBNET}:$((CAMPUS + 32))::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 traffic-filter from-nren-v6 in
 ipv6 traffic-filter to-nren-v6 out
 no shutdown
!
ip telnet source-interface Loopback0
END
}
render_interfaces=conf_interfaces_bdr_bgp

conf_bgp_bdr_bgp () {
  cat <<END
!
router bgp ${CAMPUS}0
 no bgp default ipv4-unicast
 bgp deterministic-med
 bgp router-id ${CAMPUS_LOOP_V4_SUBNET}.241
!
 address-family ipv4
  network ${CAMPUS_CORE_V4_SUBNET}.0 mask 255.255.255.0
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.242 remote-as ${CAMPUS}0
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.242 update-source loopback 0
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.242 description iBGP with Core Router
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.242 activate
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST - 1)) remote-as 65534
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST - 1)) description eBGP with transit1.nren
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST - 1)) prefix-list NREN-in in
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST - 1)) prefix-list Campus${CAMPUS}-out out
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST - 1)) activate
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST + 127)) remote-as 65534
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST + 127)) description eBGP with transit2.nren
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST + 127)) prefix-list NREN-in in
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST + 127)) prefix-list Campus${CAMPUS}-out out
  neighbor ${NREN_V4_SUBNET}.$((NREN_V4_HOST + 127)) activate
  distance bgp 200 200 200
!
 address-family ipv6
  network ${CAMPUS_V6_BLOCK}::/48
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::242 remote-as ${CAMPUS}0
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::242 update-source loopback0
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::242 description iBGP with Core Router
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::242 activate
  neighbor ${NREN_V6_SUBNET}:${CAMPUS}::0 remote-as 65534
  neighbor ${NREN_V6_SUBNET}:${CAMPUS}::0 description eBGP with transit1.nren
  neighbor ${NREN_V6_SUBNET}:${CAMPUS}::0 prefix-list NREN-v6in in
  neighbor ${NREN_V6_SUBNET}:${CAMPUS}::0 prefix-list Campus${CAMPUS}-v6out out
  neighbor ${NREN_V6_SUBNET}:${CAMPUS}::0 activate
  neighbor ${NREN_V6_SUBNET}:$((CAMPUS + 32))::0 remote-as 65534
  neighbor ${NREN_V6_SUBNET}:$((CAMPUS + 32))::0 description eBGP with transit2.nren
  neighbor ${NREN_V6_SUBNET}:$((CAMPUS + 32))::0 prefix-list NREN-v6in in
  neighbor ${NREN_V6_SUBNET}:$((CAMPUS + 32))::0 prefix-list Campus${CAMPUS}-v6out out
  neighbor ${NREN_V6_SUBNET}:$((CAMPUS + 32))::0 activate
  distance bgp 200 200 200
END
}
render_bgp=conf_bgp_bdr_bgp

conf_routemap_bdr_bgp () {
  cat <<END
!
ip prefix-list NREN-in permit 0.0.0.0/0
!
ip prefix-list Campus${CAMPUS}-out permit ${CAMPUS_CORE_V4_SUBNET}.0/24
!
ipv6 prefix-list NREN-v6in permit ::/0
!
ipv6 prefix-list Campus${CAMPUS}-v6out permit ${CAMPUS_V6_BLOCK}::/48
END
}
render_routemap=conf_routemap_bdr_bgp

conf_static_bdr_bgp () {
  cat <<END
!
ip route ${CAMPUS_CORE_V4_SUBNET}.0 255.255.255.0 Null0
ip route ${CAMPUS_V4_BLOCK}.0.0 255.255.0.0 Null0
!
ipv6 route ${CAMPUS_V6_BLOCK}::/48 Null0
END
}
render_static=conf_static_bdr_bgp

return 2>/dev/null || render "$@"
