#!/bin/bash -eu
. "04-ibgp/$(basename "$0")"
cat <<EOS
interface GigabitEthernet2
 description Link to Transit Provider AS${ISP_AS}
 ip address ${ISP_LOCAL_V4} 255.255.255.254
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address ${ISP_LOCAL_V6}/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
router isis as${AS}
 default-information originate route-map DEFAULT-ORIG
 !
 address-family ipv6
  default-information originate route-map DEFAULT-ORIGv6
 exit-address-family
!
router bgp ${AS}
 neighbor ${ISP_REMOTE_V6} remote-as ${ISP_AS}
 neighbor ${ISP_REMOTE_V6} description eBGP with TRANSIT AS${ISP_AS}
 neighbor ${ISP_REMOTE_V6} password 7 106C2E29091610
 neighbor ${ISP_REMOTE_V4} remote-as ${ISP_AS}
 neighbor ${ISP_REMOTE_V4} description eBGP with TRANSIT AS${ISP_AS}
 neighbor ${ISP_REMOTE_V4} password 7 04792C3603204E
 !
 address-family ipv4
  neighbor ${ISP_REMOTE_V4} activate
  neighbor ${ISP_REMOTE_V4} prefix-list FULL-ROUTES in
  neighbor ${ISP_REMOTE_V4} prefix-list AS${AS}-block out
  neighbor ${ISP_REMOTE_V4} route-map Transit-in in
 exit-address-family
 !
 address-family ipv6
  neighbor ${ISP_REMOTE_V6} activate
  neighbor ${ISP_REMOTE_V6} prefix-list FULL-v6ROUTES in
  neighbor ${ISP_REMOTE_V6} prefix-list AS${AS}-v6block out
  neighbor ${ISP_REMOTE_V6} route-map Transitv6-in in
 exit-address-family
!
ip prefix-list AS${AS}-block permit 100.68.${GROUP}.0/24
!
ip prefix-list DEFAULT-ROUTE permit 0.0.0.0/0
!
ip prefix-list FULL-ROUTES permit 0.0.0.0/0 le 32
!
ipv6 prefix-list AS${AS}-v6block permit 2001:DB8:${GROUP}::/48
!
ipv6 prefix-list DEFAULT-v6ROUTE permit ::/0
!
ipv6 prefix-list FULL-v6ROUTES permit ::/0 le 128
route-map Transitv6-in permit 10
 match ipv6 address prefix-list DEFAULT-v6ROUTE
 set community no-advertise
!
route-map Transitv6-in permit 20
!
route-map DEFAULT-ORIGv6 permit 10
 match ipv6 address prefix-list DEFAULT-v6ROUTE
!
route-map Transit-in permit 10
 match ip address prefix-list DEFAULT-ROUTE
 set community no-advertise
!
route-map Transit-in permit 20
!
route-map DEFAULT-ORIG permit 10
 match ip address prefix-list DEFAULT-ROUTE
EOS
return 2>/dev/null || echo "end"
