#!/bin/bash -eu
. common-C
preamble_iosv
cat <<EOS
interface Loopback0
 description Loopback on C${GROUP}
 ip address 100.68.${GROUP}.2 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::2/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/0
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to B${GROUP}
 ip address 100.68.${GROUP}.16 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ip router isis as${AS}
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:10::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
!
interface GigabitEthernet0/2
 description P2P Ethernet Link to P${GROUP}
 ip address 100.68.${GROUP}.18 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ip router isis as${AS}
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:11::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
!
interface GigabitEthernet0/3
 description P2P Ethernet Link to A${GROUP}
 ip address 100.68.${GROUP}.20 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ip router isis as${AS}
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:12::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
!
interface GigabitEthernet0/4
 description P2P Ethernet Link to SRV${GROUP}
 ip address 100.68.${GROUP}.29 255.255.255.252
 no ip redirects
 no ip proxy-arp
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:21::29/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
router isis as${AS}
 net 49.0001.000${GROUP}.0002.00
 is-type level-2-only
 authentication mode md5 level-2
 authentication key-chain as${AS}-key level-2
 metric-style wide
 set-overload-bit on-startup wait-for-bgp
 log-adjacency-changes all
 metric 100000
 passive-interface Loopback0
 !
 address-family ipv6
  multi-topology
  set-overload-bit on-startup wait-for-bgp
  metric 100000
 exit-address-family
!
router bgp ${AS}
 bgp log-neighbor-changes
 bgp deterministic-med
 no bgp default ipv4-unicast
 neighbor ibgp-full peer-group
 neighbor ibgp-full remote-as ${AS}
 neighbor ibgp-full description Full Routes
 neighbor ibgp-full password 7 0529213F2D4D4C
 neighbor ibgp-full update-source Loopback0
 neighbor ibgpv6-full peer-group
 neighbor ibgpv6-full remote-as ${AS}
 neighbor ibgpv6-full description Full Routes
 neighbor ibgpv6-full password 7 03267C3B0A0E23
 neighbor ibgpv6-full update-source Loopback0
 neighbor ibgp-partial peer-group
 neighbor ibgp-partial remote-as ${AS}
 neighbor ibgp-partial description Local Routes only
 neighbor ibgp-partial password 7 0224236B07070D
 neighbor ibgp-partial update-source Loopback0
 neighbor ibgpv6-partial peer-group
 neighbor ibgpv6-partial remote-as ${AS}
 neighbor ibgpv6-partial description Local Routes only
 neighbor ibgpv6-partial password 7 106C2E29091610
 neighbor ibgpv6-partial update-source Loopback0
 neighbor 2001:DB8:${GROUP}::1 peer-group ibgpv6-full
 neighbor 2001:DB8:${GROUP}::1 description iBGP with Border
 neighbor 2001:DB8:${GROUP}::3 peer-group ibgpv6-partial
 neighbor 2001:DB8:${GROUP}::3 description iBGP with Peering
 neighbor 2001:DB8:${GROUP}::4 peer-group ibgpv6-partial
 neighbor 2001:DB8:${GROUP}::4 description iBGP with Access
 neighbor 100.68.${GROUP}.1 peer-group ibgp-full
 neighbor 100.68.${GROUP}.1 description iBGP with Border
 neighbor 100.68.${GROUP}.3 peer-group ibgp-partial
 neighbor 100.68.${GROUP}.3 description iBGP with Peering
 neighbor 100.68.${GROUP}.4 peer-group ibgp-partial
 neighbor 100.68.${GROUP}.4 description iBGP with Access
 !
 address-family ipv4
  network 100.68.${GROUP}.0 mask 255.255.255.0 route-map set-aggregate-community
  network 100.68.${GROUP}.28 mask 255.255.255.252 route-map set-subnet-community
  neighbor ibgp-full send-community
  neighbor ibgp-full route-reflector-client
  neighbor ibgp-full next-hop-self
  neighbor ibgp-partial send-community
  neighbor ibgp-partial route-reflector-client
  neighbor ibgp-partial next-hop-self
  neighbor ibgp-partial route-map partial-iBGP out
  neighbor 100.68.${GROUP}.1 activate
  neighbor 100.68.${GROUP}.3 activate
  neighbor 100.68.${GROUP}.4 activate
  distance bgp 200 200 200
 exit-address-family
 !
 address-family ipv6
  distance bgp 200 200 200
  network 2001:DB8:${GROUP}::/48 route-map set-aggregate-community
  network 2001:DB8:${GROUP}:21::/64 route-map set-subnet-community
  neighbor ibgpv6-full send-community
  neighbor ibgpv6-full route-reflector-client
  neighbor ibgpv6-full next-hop-self
  neighbor ibgpv6-partial send-community
  neighbor ibgpv6-partial route-reflector-client
  neighbor ibgpv6-partial next-hop-self
  neighbor ibgpv6-partial route-map partial-iBGP out
  neighbor 2001:DB8:${GROUP}::1 activate
  neighbor 2001:DB8:${GROUP}::3 activate
  neighbor 2001:DB8:${GROUP}::4 activate
 exit-address-family
!
ip forward-protocol nd
!
ip bgp-community new-format
ip community-list standard aggregate permit ${AS}:1000
ip community-list standard subnets permit ${AS}:1001
ip community-list standard customer-pi permit ${AS}:1005
ip community-list standard private-peer permit ${AS}:1100
ip community-list standard bilateral-peer permit ${AS}:1200
ip community-list standard RS-peer permit ${AS}:1300
!
no ip http server
no ip http secure-server
ip route 100.68.${GROUP}.0 255.255.255.0 Null0
!
ipv6 route 2001:DB8:${GROUP}::/48 Null0
ipv6 ioam timestamp
!
route-map set-subnet-community permit 5
 description Set community on Server subnet
 set community ${AS}:1001
!
route-map partial-iBGP permit 5
 match community aggregate subnets customer-pi
!
route-map set-aggregate-community permit 5
 description Set community on Aggregate
 set community ${AS}:1000
!
EOS
postamble_iosv
