#!/bin/bash -eu
. common-B
cat <<EOS
!
version 15.7
service timestamps debug datetime msec
service timestamps log datetime msec
service password-encryption
!
hostname B${GROUP}
!
boot-start-marker
boot-end-marker
!
!
no logging console
enable secret 5 \$1\$b3/k\$jNHoF35fzOxYKUTFO0Ef3/
!
aaa new-model
!
!
aaa authentication login default local
aaa authentication enable default enable
!
!
!
!
!
aaa session-id common
!
!
!
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
no ip source-route
!
!
!
!
!
!
no ip domain lookup
ip domain name ws.nsrc.org
ip cef
no ipv6 source-route
ipv6 unicast-routing
ipv6 cef
!
multilink bundle-name authenticated
!
!
!
key chain as${AS}-key
 key 1
  key-string 7 0706325C42081B
!
!
username isplab secret 5 \$1\$vPNP\$hA1Tq3C05ByW2G31WA0wh0
!
redundancy
!
!
ip tcp path-mtu-discovery
!
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 description Loopback on B${GROUP}
 ip address 100.68.${GROUP}.1 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::1/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/0
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.17 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ip router isis as${AS}
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:10::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
!
interface GigabitEthernet0/2
 description Link to Transit Provider AS121
 ip address 100.121.1.$((GROUP*2-1)) 255.255.255.254
 no ip redirects
 no ip proxy-arp
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:18:0:$((GROUP+9))::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet0/3
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
interface GigabitEthernet0/4
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
router isis as${AS}
 net 49.0001.000${GROUP}.0001.00
 is-type level-2-only
 authentication mode md5 level-2
 authentication key-chain as${AS}-key level-2
 metric-style wide
 set-overload-bit on-startup wait-for-bgp
 log-adjacency-changes all
 metric 100000
 passive-interface Loopback0
 default-information originate route-map DEFAULT-ORIG
 !
 address-family ipv6
  multi-topology
  set-overload-bit on-startup wait-for-bgp
  metric 100000
  default-information originate route-map DEFAULT-ORIGv6
 exit-address-family
!
router bgp ${AS}
 bgp log-neighbor-changes
 bgp deterministic-med
 no bgp default ipv4-unicast
 neighbor ibgp-rr peer-group
 neighbor ibgp-rr remote-as ${AS}
 neighbor ibgp-rr description iBGP with RR
 neighbor ibgp-rr password 7 123B22271E0A0E
 neighbor ibgp-rr update-source Loopback0
 neighbor ibgpv6-rr peer-group
 neighbor ibgpv6-rr remote-as ${AS}
 neighbor ibgpv6-rr description iBGP with RR
 neighbor ibgpv6-rr password 7 123B22271E0A0E
 neighbor ibgpv6-rr update-source Loopback0
 neighbor 2001:18:0:$((GROUP+9)):: remote-as 121
 neighbor 2001:18:0:$((GROUP+9)):: description eBGP with TRANSIT AS121
 neighbor 2001:18:0:$((GROUP+9)):: password 7 106C2E29091610
 neighbor 2001:DB8:${GROUP}::2 peer-group ibgpv6-rr
 neighbor 2001:DB8:${GROUP}::2 description iBGP with Core
 neighbor 100.68.${GROUP}.2 peer-group ibgp-rr
 neighbor 100.68.${GROUP}.2 description iBGP with Core
 neighbor 100.121.1.$((GROUP*2-2)) remote-as 121
 neighbor 100.121.1.$((GROUP*2-2)) description eBGP with TRANSIT AS121
 neighbor 100.121.1.$((GROUP*2-2)) password 7 04792C3603204E
 !
 address-family ipv4
  neighbor ibgp-rr send-community
  neighbor ibgp-rr next-hop-self
  neighbor 100.68.${GROUP}.2 activate
  neighbor 100.121.1.$((GROUP*2-2)) activate
  neighbor 100.121.1.$((GROUP*2-2)) prefix-list FULL-ROUTES in
  neighbor 100.121.1.$((GROUP*2-2)) route-map Transit-in in
  neighbor 100.121.1.$((GROUP*2-2)) route-map Transit-out out
  distance bgp 200 200 200
 exit-address-family
 !
 address-family ipv6
  distance bgp 200 200 200
  neighbor ibgpv6-rr send-community
  neighbor ibgpv6-rr next-hop-self
  neighbor 2001:18:0:$((GROUP+9)):: activate
  neighbor 2001:18:0:$((GROUP+9)):: prefix-list FULL-v6ROUTES in
  neighbor 2001:18:0:$((GROUP+9)):: route-map Transitv6-in in
  neighbor 2001:18:0:$((GROUP+9)):: route-map Transit-out out
  neighbor 2001:DB8:${GROUP}::2 activate
 exit-address-family
!
ip forward-protocol nd
!
ip bgp-community new-format
ip community-list standard aggregate permit ${AS}:1000
ip community-list standard subnets permit ${AS}:1001
ip community-list standard customer-pi permit ${AS}:1005
ip community-list standard private-peer permit ${AS}:1100
ip community-list standard bilateral-peer permit ${AS}:1200
ip community-list standard RS-peer permit ${AS}:1300
!
no ip http server
no ip http secure-server
!
!
ip prefix-list DEFAULT-ROUTE seq 5 permit 0.0.0.0/0
!
ip prefix-list FULL-ROUTES seq 5 permit 0.0.0.0/0
ipv6 ioam timestamp
!
!
ipv6 prefix-list DEFAULT-v6ROUTE seq 5 permit ::/0
!
ipv6 prefix-list FULL-v6ROUTES seq 5 permit ::/0
route-map Transit-out permit 5
 match community aggregate customer-pi
!
route-map Transitv6-in permit 10
 match ipv6 address prefix-list DEFAULT-v6ROUTE
 set community no-advertise
!
route-map Transitv6-in permit 20
 description Local pref for Upstream routes
 set local-preference 50
!
route-map DEFAULT-ORIGv6 permit 10
 match ipv6 address prefix-list DEFAULT-v6ROUTE
!
route-map Transit-in permit 10
 match ip address prefix-list DEFAULT-ROUTE
 set community no-advertise
!
route-map Transit-in permit 20
 description Local pref for Upstream routes
 set local-preference 50
!
route-map DEFAULT-ORIG permit 10
 match ip address prefix-list DEFAULT-ROUTE
!
!
!
!
!
control-plane
!
no banner exec
banner incoming ^
**************************************************************************
* IOSv is strictly limited to use for evaluation, demonstration and IOS  *
* education. IOSv is provided as-is and is not supported by Cisco's      *
* Technical Advisory Center. Any use or disclosure, in whole or in part, *
* of the IOSv Software or Documentation to any third party for any       *
* purposes is expressly prohibited except as otherwise authorized by     *
* Cisco in writing.                                                      *
**************************************************************************^
banner login ^
             BGP Peering/IXP Workshop
          Network Startup Resource Center
^
!
line con 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line aux 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line vty 0 4
 exec-timeout 0 0
 transport preferred none
 transport input telnet ssh
!
no scheduler allocate
!
end
EOS
