#!/bin/bash -eu
. l2-2-ip/gen-distX
PRIORITY=12288

conf_stp_dist_stp () {
cat <<END
!
spanning-tree mode mst
spanning-tree mst 0 priority ${PRIORITY}
END
}
render_stp=conf_stp_dist_stp

return 2>/dev/null || render_flat "$@"
