#!/bin/bash -eu
. l2-2-ip/gen-edgeX
PRIORITY=24576

conf_stp_edge_stp () {
cat <<END
!
spanning-tree mode mst
spanning-tree mst 0 priority ${PRIORITY}
END
}
render_stp=conf_stp_edge_stp

return 2>/dev/null || render_flat "$@"
