#!/bin/bash -eu
. l2-2-ip/gen-distX
PRIORITY=12288

conf_vlans_dist_stp () {
  cat <<END
!
vtp mode off
END
}
render_vlans=conf_vlans_dist_stp

conf_stp_dist_stp () {
cat <<END
!
spanning-tree vlan 1 priority ${PRIORITY}
END
}
render_stp=conf_stp_dist_stp

return 2>/dev/null || render_flat "$@"
