#!/bin/bash -eu
. l2-2-ip/gen-coreX
PRIORITY=0

conf_stp_core_stp () {
cat <<END
!
spanning-tree mode mst
spanning-tree mst 0 priority ${PRIORITY}
END
}
render_stp=conf_stp_core_stp

return 2>/dev/null || render "$@"
