#!/bin/bash -eu
. common-Cust
preamble_iosv N
cat <<EOS
interface Loopback0
 description Address anchor for Customer ${GROUP}
 ip address 100.68.${GROUP}.64 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}:4000::/128
!
interface Loopback1
 description Address anchor for new block
 ip address 100.68.$(( GROUP+100 )).1 255.255.255.255
 ipv6 address 2001:DB8:$(( GROUP+100 ))::1/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/0
 description P2P Ethernet Link to A${OTHER}
 ip address 100.68.${OTHER}.37 255.255.255.254
 no ip redirects
 no ip proxy-arp
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${OTHER}:32::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to A${GROUP}
 ip address 100.68.${GROUP}.35 255.255.255.254
 no ip redirects
 no ip proxy-arp
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:31::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet0/2
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
interface GigabitEthernet0/3
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
router bgp ${AS}
 bgp log-neighbor-changes
 bgp deterministic-med
 no bgp default ipv4-unicast
 neighbor 2001:DB8:${GROUP}:31:: remote-as ${ISPA_AS}
 neighbor 2001:DB8:${OTHER}:32:: remote-as ${ISPB_AS}
 neighbor 100.68.${GROUP}.34 remote-as ${ISPA_AS}
 neighbor 100.68.${OTHER}.36 remote-as ${ISPB_AS}
 !
 address-family ipv4
  network 100.68.$(( GROUP+100 )).0 mask 255.255.255.0
  neighbor 100.68.${GROUP}.34 activate
  neighbor 100.68.${GROUP}.34 prefix-list Group${GROUP}-in in
  neighbor 100.68.${GROUP}.34 prefix-list Cust${GROUP}-out out
  neighbor 100.68.${OTHER}.36 activate
  neighbor 100.68.${OTHER}.36 prefix-list Group${OTHER}-in in
  neighbor 100.68.${OTHER}.36 prefix-list Cust${GROUP}-out out
  distance bgp 200 200 200
 exit-address-family
 !
 address-family ipv6
  distance bgp 200 200 200
  network 2001:DB8:$(( GROUP+100 ))::/48
  neighbor 2001:DB8:${GROUP}:31:: activate
  neighbor 2001:DB8:${GROUP}:31:: prefix-list Group${GROUP}v6-in in
  neighbor 2001:DB8:${GROUP}:31:: prefix-list Cust${GROUP}-v6out out
  neighbor 2001:DB8:${OTHER}:32:: activate
  neighbor 2001:DB8:${OTHER}:32:: prefix-list Group${OTHER}v6-in in
  neighbor 2001:DB8:${OTHER}:32:: prefix-list Cust${GROUP}-v6out out
 exit-address-family
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
ip route 100.68.${GROUP}.64 255.255.255.192 Null0
ip route 100.68.$(( GROUP+100 )).0 255.255.255.0 Null0
!
!
ip prefix-list Cust${GROUP}-out seq 5 permit 100.68.$(( GROUP+100 )).0/24
!
ip prefix-list Group${GROUP}-in seq 5 permit 0.0.0.0/0
ip prefix-list Group${GROUP}-in seq 10 permit 100.68.${GROUP}.0/24
ip prefix-list Group${GROUP}-in seq 15 permit 100.68.$(( OTHER+100 )).0/24
!
ip prefix-list Group${OTHER}-in seq 5 permit 0.0.0.0/0
ip prefix-list Group${OTHER}-in seq 10 permit 100.68.${OTHER}.0/24
ip prefix-list Group${OTHER}-in seq 15 permit 100.68.$(( OTHER+100 )).0/24
ipv6 route 2001:DB8:${GROUP}:4000::/52 Null0
ipv6 route 2001:DB8:$(( GROUP+100 ))::/48 Null0
ipv6 ioam timestamp
!
!
ipv6 prefix-list Cust${GROUP}-v6out seq 5 permit 2001:DB8:$(( GROUP+100 ))::/48
!
ipv6 prefix-list Group${GROUP}v6-in seq 5 permit ::/0
ipv6 prefix-list Group${GROUP}v6-in seq 10 permit 2001:DB8:${GROUP}::/48
ipv6 prefix-list Group${GROUP}v6-in seq 15 permit 2001:DB8:$(( OTHER+100 ))::/48
!
ipv6 prefix-list Group${OTHER}v6-in seq 5 permit ::/0
ipv6 prefix-list Group${OTHER}v6-in seq 10 permit 2001:DB8:${OTHER}::/48
ipv6 prefix-list Group${OTHER}v6-in seq 15 permit 2001:DB8:$(( OTHER+100 ))::/48
EOS
postamble_iosv
