#!/bin/bash -eu
. common-A
preamble_csrv N
cat <<EOS
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface Loopback0
 description Loopback on A${GROUP}
 ip address 100.68.${GROUP}.4 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::4/128
!
interface GigabitEthernet1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.21 255.255.255.254
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address 2001:DB8:${GROUP}:12::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet2
 description P2P Ethernet Link to Cust${GROUP}
 ip address 100.68.${GROUP}.34 255.255.255.254
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address 2001:DB8:${GROUP}:31::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
EOS
postamble_csrv
