#!/bin/bash -eu
. common-C
preamble_csrv N
cat <<EOS
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface Loopback0
 description Loopback on C${GROUP}
 ip address 100.68.${GROUP}.2 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::2/128
!
interface GigabitEthernet1
 description P2P Ethernet Link to B${GROUP}
 ip address 100.68.${GROUP}.16 255.255.255.254
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address 2001:DB8:${GROUP}:10::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet2
 description P2P Ethernet Link to P${GROUP}
 ip address 100.68.${GROUP}.18 255.255.255.254
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address 2001:DB8:${GROUP}:11::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet3
 description P2P Ethernet Link to A${GROUP}
 ip address 100.68.${GROUP}.20 255.255.255.254
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address 2001:DB8:${GROUP}:12::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet4
 description P2P Ethernet Link to SRV${GROUP}
 ip address 100.68.${GROUP}.29 255.255.255.252
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address 2001:DB8:${GROUP}:21::29/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet5
 no ip address
 shutdown
EOS
postamble_csrv
