#!/bin/bash -eu
. common-P
preamble_csrv N
cat <<EOS
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface Loopback0
 description Loopback on P${GROUP}
 ip address 100.68.${GROUP}.3 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::3/128
!
interface GigabitEthernet1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.19 255.255.255.254
 no ip redirects
 no ip proxy-arp
 no shutdown
 ipv6 address 2001:DB8:${GROUP}:11::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
EOS
postamble_csrv
