#!/bin/bash -eu
. "00-base/$(basename "$0")"
. setup-iosv
cat <<EOS
interface Loopback0
 description Address anchor for Customer ${GROUP}
 ip address 100.68.${GROUP}.64 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}:4000::/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to A${GROUP}
 ip address 100.68.${GROUP}.35 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ipv6 address 2001:DB8:${GROUP}:31::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
EOS
return 2>/dev/null || echo "end"
