#!/bin/bash -eu
. "03-sec/$(basename "$0")"
cat <<EOS
ip route 0.0.0.0 0.0.0.0 100.68.${GROUP}.34
ip route 100.68.${GROUP}.64 255.255.255.192 Null0
!
ipv6 route 2001:DB8:${GROUP}:4000::/52 Null0
ipv6 route ::/0 2001:DB8:${GROUP}:31::
!
EOS
return 2>/dev/null || echo "end"
