#!/bin/bash -eu
. "03-sec/$(basename "$0")"
cat <<EOS
router bgp ${AS}
 bgp log-neighbor-changes
 bgp deterministic-med
 no bgp default ipv4-unicast
 neighbor ibgp-full peer-group
 neighbor ibgp-full remote-as ${AS}
 neighbor ibgp-full description Full Routes
 neighbor ibgp-full password 7 0529213F2D4D4C
 neighbor ibgp-full update-source Loopback0
 neighbor ibgpv6-full peer-group
 neighbor ibgpv6-full remote-as ${AS}
 neighbor ibgpv6-full description Full Routes
 neighbor ibgpv6-full password 7 03267C3B0A0E23
 neighbor ibgpv6-full update-source Loopback0
 neighbor ibgp-partial peer-group
 neighbor ibgp-partial remote-as ${AS}
 neighbor ibgp-partial description Local Routes only
 neighbor ibgp-partial password 7 0224236B07070D
 neighbor ibgp-partial update-source Loopback0
 neighbor ibgpv6-partial peer-group
 neighbor ibgpv6-partial remote-as ${AS}
 neighbor ibgpv6-partial description Local Routes only
 neighbor ibgpv6-partial password 7 106C2E29091610
 neighbor ibgpv6-partial update-source Loopback0
 neighbor 2001:DB8:${GROUP}::1 peer-group ibgpv6-full
 neighbor 2001:DB8:${GROUP}::1 description iBGP with Border
 neighbor 2001:DB8:${GROUP}::3 peer-group ibgpv6-partial
 neighbor 2001:DB8:${GROUP}::3 description iBGP with Peering
 neighbor 2001:DB8:${GROUP}::4 peer-group ibgpv6-partial
 neighbor 2001:DB8:${GROUP}::4 description iBGP with Access
 neighbor 100.68.${GROUP}.1 peer-group ibgp-full
 neighbor 100.68.${GROUP}.1 description iBGP with Border
 neighbor 100.68.${GROUP}.3 peer-group ibgp-partial
 neighbor 100.68.${GROUP}.3 description iBGP with Peering
 neighbor 100.68.${GROUP}.4 peer-group ibgp-partial
 neighbor 100.68.${GROUP}.4 description iBGP with Access
 !
 address-family ipv4
  network 100.68.${GROUP}.0 mask 255.255.255.0
  network 100.68.${GROUP}.28 mask 255.255.255.252
  neighbor ibgp-full send-community
  neighbor ibgp-full route-reflector-client
  neighbor ibgp-full next-hop-self
  neighbor ibgp-partial send-community
  neighbor ibgp-partial route-reflector-client
  neighbor ibgp-partial next-hop-self
  neighbor ibgp-partial filter-list 10 out
  neighbor 100.68.${GROUP}.1 activate
  neighbor 100.68.${GROUP}.3 activate
  neighbor 100.68.${GROUP}.4 activate
  distance bgp 200 200 200
 exit-address-family
 !
 address-family ipv6
  distance bgp 200 200 200
  network 2001:DB8:${GROUP}::/48
  network 2001:DB8:${GROUP}:21::/64
  neighbor ibgpv6-full send-community
  neighbor ibgpv6-full route-reflector-client
  neighbor ibgpv6-full next-hop-self
  neighbor ibgpv6-partial send-community
  neighbor ibgpv6-partial route-reflector-client
  neighbor ibgpv6-partial next-hop-self
  neighbor ibgpv6-partial filter-list 10 out
  neighbor 2001:DB8:${GROUP}::1 activate
  neighbor 2001:DB8:${GROUP}::3 activate
  neighbor 2001:DB8:${GROUP}::4 activate
 exit-address-family
!
ip as-path access-list 10 permit ^$
!
ip route 100.68.${GROUP}.0 255.255.255.0 Null0
!
ipv6 route 2001:DB8:${GROUP}::/48 Null0
!
EOS
return 2>/dev/null || echo "end"
