#!/bin/bash -eu
. l3-2-ip/gen-coreX

conf_interfaces_core_ospf () {
  cat <<END
!
interface Loopback 0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.242 255.255.255.255
 ip ospf 41 area 0
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::242/128
 ipv6 ospf 41 area 0
 no shutdown
!
interface GigabitEthernet0/0
 no switchport
 description CAMPUS CORE to BORDER
 ip address ${CAMPUS_CORE_V4_SUBNET}.2 255.255.255.240
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::2/64
 ipv6 ospf 41 area 0
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
END
  trunk GigabitEthernet0/1 10-12 "Trunk Link to dist1-b1.campus${CAMPUS}"
  trunk GigabitEthernet0/2 20-22 "Trunk Link to dist1-b2.campus${CAMPUS}"
cat <<END
!
interface GigabitEthernet0/3
 no switchport
 description Network Management and Monitoring
 ip address ${CAMPUS_SRVR_V4_SUBNET}.129 255.255.255.240
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_SRVR_V6_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan11
 description Staff VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STAFF_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STAFF_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan12
 description Student VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan21
 description Staff VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STAFF_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STAFF_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan22
 description Student VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
END
}
render_interfaces=conf_interfaces_core_ospf

conf_igp_core_ospf () {
  cat <<END
!
router ospf 41
 router-id ${CAMPUS_LOOP_V4_SUBNET}.242
 log-adjacency-changes
 passive-interface default
 no passive-interface GigabitEthernet0/0
!
ipv6 router ospf 41
 router-id ${CAMPUS_LOOP_V4_SUBNET}.242
 log-adjacency-changes
 passive-interface default
 no passive-interface GigabitEthernet0/0
END
}
render_igp=conf_igp_core_ospf

## We should not need static routes...
#render_static=conf_null

# However, since IOSvL2 doesn't support OSPFv3, we still need them
conf_static_core_ospf () {
  cat <<END
!
ipv6 route ::/0 ${CAMPUS_CORE_V6_SUBNET}::1
ipv6 route ${CAMPUS_V6_BLOCK}::/48 Null0
ipv6 route ${CAMPUS_LOOP_V6_SUBNET}::241/128 ${CAMPUS_CORE_V6_SUBNET}::1
END
}
render_static=conf_static_core_ospf

return 2>/dev/null || render "$@"
