#!/bin/bash -eu
. "16-rov-state/$(basename "$0")"
cat <<EOS
router bgp ${AS}
 address-family ipv4
  neighbor ${PEER_REMOTE_V4} maximum-prefix 25
  neighbor ${IXP_V4IXP}.254 maximum-prefix 40
 exit-address-family
 !
 address-family ipv6
  neighbor ${PEER_REMOTE_V6} maximum-prefix 25
  neighbor ${IXP_V6BLOCK}:1::FE maximum-prefix 40
 exit-address-family
!
ip prefix-list RTBH-filter permit 61.45.248.0/21 ge 32
!
EOS
return 2>/dev/null || echo "end"
