#!/bin/bash -eu
. "15-rov/$(basename "$0")"
cat <<EOS
router bgp ${AS}
 address-family ipv4
  bgp bestpath prefix-validate allow-invalid
  neighbor ibgp-full send-community both
  neighbor ibgp-full announce rpki state
  neighbor ibgp-partial send-community both
  neighbor ibgp-partial announce rpki state
 exit-address-family
 !
 address-family ipv6
  bgp bestpath prefix-validate allow-invalid
  neighbor ibgpv6-full send-community both
  neighbor ibgpv6-full announce rpki state
  neighbor ibgpv6-partial send-community both
  neighbor ibgpv6-partial announce rpki state
 exit-address-family
!
EOS
return 2>/dev/null || echo "end"
