#!/bin/bash -eu
. common-IXP
cat <<EOS
!
version 15.2
service timestamps debug datetime msec localtime show-timezone year
service timestamps log datetime msec localtime show-timezone year
no service password-encryption
!
hostname ${HOSTNAME}
!
boot-start-marker
boot-end-marker
!
!
no logging console
enable secret 5 \$1\$ZCOO\$vZTX3iEGGRRL2pjvcg/hR1
!
username isplab secret 5 \$1\$vPNP\$hA1Tq3C05ByW2G31WA0wh0
username nsrc secret 5 \$1\$cu34\$XyyIkFaE6f9LLcnPxQEuy/
aaa new-model
!
!
aaa authentication login default local
aaa authentication enable default enable
!
!
!
!
!
!
aaa session-id common
!
!
!
!
!
vtp mode off
no ip source-route
no ip routing
!
!
!
no ip domain-lookup
ip domain-name ws.nsrc.org
ip name-server 192.168.122.1
no ip cef
no ipv6 source-route
no ipv6 cef
!
!
!
spanning-tree mode mst
spanning-tree extend system-id
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface GigabitEthernet0/0
 description P1
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet0/1
 description P2
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet0/2
 description P3
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet0/3
 description P4
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet1/0
 description P5
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet1/1
 description P6
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet1/2
 description P7
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet1/3
 description P8
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet2/0
 shutdown
 negotiation auto
!
interface GigabitEthernet2/1
 shutdown
 negotiation auto
!
interface GigabitEthernet2/2
 shutdown
 negotiation auto
!
interface GigabitEthernet2/3
 shutdown
 negotiation auto
!
interface GigabitEthernet3/0
 shutdown
 negotiation auto
!
interface GigabitEthernet3/1
 description Route server RS${DEV}
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet3/2
 description Service router SR${DEV}
 switchport mode access
 negotiation auto
 spanning-tree portfast edge
 spanning-tree bpduguard enable
!
interface GigabitEthernet3/3
 description Management interface
 no switchport
 ip address ${V4SRV}.2 255.255.255.248
 no ip redirects
 no ip proxy-arp
 negotiation auto
 ipv6 address ${V6BLOCK}::2/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
ip default-gateway ${V4SRV}.1
ip forward-protocol nd
!
ip tcp path-mtu-discovery
no ip http server
!
ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
!
!
ipv6 route ::/0 ${V6BLOCK}::1
!
!
!
snmp-server community NetManage RO
snmp-server location NSRC Workshop
snmp ifmib ifindex persist
!
!
!
control-plane
!
banner exec ^
^
banner incoming ^
**************************************************************************
* IOSv is strictly limited to use for evaluation, demonstration and IOS  *
* education. IOSv is provided as-is and is not supported by Cisco's      *
* Technical Advisory Center. Any use or disclosure, in whole or in part, *
* of the IOSv Software or Documentation to any third party for any       *
* purposes is expressly prohibited except as otherwise authorized by     *
* Cisco in writing.                                                      *
**************************************************************************^
banner login ^
Routing Infrastructure and Security Operations Workshop Lab
          Network Startup Resource Center
^
!
line con 0
 exec-timeout 0 0
 transport preferred none
line aux 0
 exec-timeout 0 0
 transport preferred none
line vty 0 4
 transport preferred none
 transport input telnet ssh
!
!
end
EOS
