#!/bin/bash -eu
. common
DEV="${1}"
IXP="${1}"
. common-ixp

# The upstream TR
TR_AS="$((DEV+120))"

TR_REMOTE_V4="100.${TR_AS}.1.$((NGROUPS*2))"
TR_LOCAL_V4="100.${TR_AS}.1.$((NGROUPS*2+1))"
TR_REMOTE_V6="2001:$((DEV+17)):0:$((NGROUPS+10))::"
TR_LOCAL_V6="${TR_REMOTE_V6}1"

cat <<EOS
!
version 15.7
!
no service timestamps debug uptime
service timestamps log datetime msec localtime show-timezone year
service password-encryption
!
hostname SR${DEV}
!
no logging console
enable secret 5 \$1\$D1SG\$A.RX6EM0i.8jY90/Pj.sy1
!
aaa new-model
!
aaa authentication login default local
aaa authentication enable default enable
!
no ip source-route
no ip icmp rate-limit unreachable
!
no ip domain lookup
ip domain name ws.nsrc.org
ip name-server 192.168.122.1
ip cef
no ipv6 source-route
ipv6 unicast-routing
ipv6 cef
!
username isplab secret 5 \$1\$vPNP\$hA1Tq3C05ByW2G31WA0wh0
username nsrc secret 5 \$1\$wSfF\$s801CqE7JfglfXMGJmbR7/
!
ip tcp path-mtu-discovery
!
interface GigabitEthernet0/0
 description Link to TR${DEV}
 ip address ${TR_LOCAL_V4} 255.255.255.254
 ip access-group OUTSIDE_IN_V4 in
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${TR_LOCAL_V6}/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 traffic-filter OUTSIDE_IN_V6 in
 shutdown
!
interface GigabitEthernet0/1
 description Link to RS${DEV}
 ip address ${IXP_V4SRV}.9 255.255.255.248
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${IXP_V6BLOCK}:2::9/64
 ipv6 nd ra suppress all
 no shutdown
!
interface GigabitEthernet0/2
 description IXP${DEV} peering LAN
 ip address ${IXP_V4IXP}.253 255.255.255.0
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${IXP_V6BLOCK}:1::FD/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
interface GigabitEthernet0/3
 description Link to IXP${DEV} management port
 ip address ${IXP_V4SRV}.1 255.255.255.248
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${IXP_V6BLOCK}::1/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
router bgp ${SR_AS}
 no bgp enforce-first-as
 bgp log-neighbor-changes
 bgp deterministic-med
 no bgp default ipv4-unicast
 neighbor ${TR_REMOTE_V6} remote-as ${TR_AS}
 neighbor ${TR_REMOTE_V6} description eBGP with TR1
 neighbor ${TR_REMOTE_V6} ttl-security hops 1
 neighbor ${TR_REMOTE_V6} password 7 096E6939150415
 neighbor ${IXP_V6BLOCK}:1::FE remote-as ${RS_AS}
 neighbor ${IXP_V6BLOCK}:1::FE description eBGP with IXP${DEV} RS
 neighbor ${IXP_V6BLOCK}:1::FE password 7 0452131642335F
 neighbor ${TR_REMOTE_V4} remote-as ${TR_AS}
 neighbor ${TR_REMOTE_V4} description eBGP with TR1
 neighbor ${TR_REMOTE_V4} ttl-security hops 1
 neighbor ${TR_REMOTE_V4} password 7 096E6939150415
 neighbor ${IXP_V4IXP}.254 remote-as ${RS_AS}
 neighbor ${IXP_V4IXP}.254 description eBGP with IXP${DEV} RS
 neighbor ${IXP_V4IXP}.254 password 7 0452131642335F
 !
 address-family ipv4
  network ${IXP_V4SRV}.0 mask 255.255.255.0
  neighbor ${TR_REMOTE_V4} activate
  neighbor ${TR_REMOTE_V4} prefix-list FULL-ROUTES in
  neighbor ${TR_REMOTE_V4} prefix-list AS${SR_AS}-block out
  neighbor ${IXP_V4IXP}.254 activate
  neighbor ${IXP_V4IXP}.254 prefix-list IXP-RS in
  neighbor ${IXP_V4IXP}.254 prefix-list AS${SR_AS}-block out
 exit-address-family
 !
 address-family ipv6
  network ${IXP_V6BLOCK}::/48
  neighbor ${TR_REMOTE_V6} activate
  neighbor ${TR_REMOTE_V6} prefix-list FULL-v6ROUTES in
  neighbor ${TR_REMOTE_V6} prefix-list AS${SR_AS}-v6block out
  neighbor ${IXP_V6BLOCK}:1::FE activate
  neighbor ${IXP_V6BLOCK}:1::FE prefix-list IXP-v6RS in
  neighbor ${IXP_V6BLOCK}:1::FE prefix-list AS${SR_AS}-v6block out
 exit-address-family
!
ip forward-protocol nd
!
ip bgp-community new-format
!
no ip http server
no ip http secure-server
ip route ${IXP_V4SRV}.0 255.255.255.0 Null0
!
ip access-list extended OUTSIDE_IN_V4
 deny   ip any ${IXP_V4IXP}.0 0.0.0.255
 permit ip any any
!
ip prefix-list AS${SR_AS}-block permit ${IXP_V4SRV}.0/24
!
ip prefix-list FULL-ROUTES permit 0.0.0.0/0 le 32
!
ip prefix-list IXP-RS description IPv4 prefixes from RouteServer
EOS
for G in $(seq "$NGROUPS"); do
  cat <<EOS
ip prefix-list IXP-RS permit 100.68.$(( G+GROUP_OFFSET )).0/24
EOS
done
for G in $(seq "$NGROUPS"); do
  cat <<EOS
ip prefix-list IXP-RS permit 100.68.$(( G+GROUP_OFFSET+100 )).0/24
EOS
done
cat <<EOS
ipv6 route ${IXP_V6BLOCK}::/48 Null0
!
ipv6 prefix-list AS${SR_AS}-v6block permit ${IXP_V6BLOCK}::/48
!
ipv6 prefix-list FULL-v6ROUTES permit ::/0 le 128
!
ipv6 prefix-list IXP-v6RS description IPv6 prefixes from RouteServer
EOS
for G in $(seq "$NGROUPS"); do
  cat <<EOS
ipv6 prefix-list IXP-v6RS permit 2001:DB8:$(( G+GROUP_OFFSET ))::/48
EOS
done
for G in $(seq "$NGROUPS"); do
  cat <<EOS
ipv6 prefix-list IXP-v6RS permit 2001:DB8:$(( G+GROUP_OFFSET+100 ))::/48
EOS
done
cat <<EOS
snmp-server community NetManage RO
snmp-server ifindex persist
snmp-server location NSRC Workshop
!
ipv6 access-list OUTSIDE_IN_V6
 deny ipv6 any ${IXP_V6BLOCK}:1::/64
 permit ipv6 any any
!
banner exec ^
^
banner incoming ^
^
banner login ^
Routing Infrastructure and Security Operations Workshop
          Network Startup Resource Center
^
!
line con 0
 exec-timeout 0 0
 transport preferred none
line aux 0
 exec-timeout 0 0
 transport preferred none
line vty 0 4
 exec-timeout 0 0
 transport preferred none
 transport input telnet ssh
!
EOS
return 2>/dev/null || echo "end"
