#!/bin/bash -eu
. common

DEV="${1}"
HOSTNAME="IXP${DEV}"

V6DEC="$(( 65536 - DEV ))"
V6BLOCK="2001:DB8:`printf "%04X" "$V6DEC"`"
V4SRV="100.127.$(( (DEV-1)*2 ))"
V4IXP="100.127.$(( (DEV-1)*2+1 ))"

GROUP_OFFSET=$(( (DEV-1)*NGROUPS ))

cat <<EOS
!
version 15.2
!
service timestamps debug datetime msec localtime show-timezone year
service timestamps log datetime msec localtime show-timezone year
no service password-encryption
!
hostname ${HOSTNAME}
!
no logging console
enable secret 5 \$1\$ZCOO\$vZTX3iEGGRRL2pjvcg/hR1
!
username isplab secret 5 \$1\$vPNP\$hA1Tq3C05ByW2G31WA0wh0
username nsrc secret 5 \$1\$cu34\$XyyIkFaE6f9LLcnPxQEuy/
aaa new-model
!
aaa authentication login default local
aaa authentication enable default enable
!
vtp mode off
no ip source-route
no ip routing
!
no ip domain-lookup
ip domain-name ws.nsrc.org
ip name-server 192.168.122.1
no ip cef
no ipv6 source-route
no ipv6 cef
!
spanning-tree mode mst
spanning-tree extend system-id
!
interface GigabitEthernet0/0
 description P$(( GROUP_OFFSET+1 ))
 switchport mode access
 spanning-tree portfast edge
 spanning-tree bpduguard enable
 no shutdown
!
interface GigabitEthernet0/1
 description P$(( GROUP_OFFSET+2 ))
 switchport mode access
 spanning-tree portfast edge
 spanning-tree bpduguard enable
 no shutdown
!
interface GigabitEthernet0/2
 description P$(( GROUP_OFFSET+3 ))
 switchport mode access
 spanning-tree portfast edge
 spanning-tree bpduguard enable
 no shutdown
!
interface GigabitEthernet0/3
 description P$(( GROUP_OFFSET+4 ))
 switchport mode access
 spanning-tree portfast edge
 spanning-tree bpduguard enable
 no shutdown
!
interface GigabitEthernet3/1
 description Route server RS${DEV}
 switchport mode access
 spanning-tree portfast edge
 spanning-tree bpduguard enable
 no shutdown
!
interface GigabitEthernet3/2
 description Service router SR${DEV}
 switchport mode access
 spanning-tree portfast edge
 spanning-tree bpduguard enable
 no shutdown
!
interface GigabitEthernet3/3
 description Management interface
 no switchport
 ip address ${V4SRV}.2 255.255.255.248
 no ip redirects
 no ip proxy-arp
 ipv6 address ${V6BLOCK}::2/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
ip default-gateway ${V4SRV}.1
ip forward-protocol nd
!
ip tcp path-mtu-discovery
no ip http server
!
ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
!
ipv6 route ::/0 ${V6BLOCK}::1
!
snmp-server community NetManage RO
snmp-server location NSRC Workshop
snmp ifmib ifindex persist
!
banner exec ^
^
banner login ^
Routing Infrastructure and Security Operations Workshop Lab
          Network Startup Resource Center
^
!
line con 0
 exec-timeout 0 0
 transport preferred none
line aux 0
 exec-timeout 0 0
 transport preferred none
line vty 0 4
 transport preferred none
 transport input telnet ssh
!
EOS
return 2>/dev/null || echo "end"
