#!/bin/bash -eu
. common-group
HOSTNAME="B${GROUP}"

GHI="$(( (GROUP-1) / NGROUPS ))"
GLO="$(( (GROUP-1) % NGROUPS ))"

ISP_AS="$(( GHI + 121 ))"
ISP_LOCAL_V4="100.$(( GHI + 121 )).1.$((GLO*2+1))"
ISP_REMOTE_V4="100.$(( GHI + 121 )).1.$((GLO*2))"
ISP_LOCAL_V6="2001:$(( GHI + 18 )):0:$((GLO+10))::1"
ISP_REMOTE_V6="2001:$(( GHI + 18 )):0:$((GLO+10))::"

cat <<EOS
!
version 16.6
!
EOS
return 2>/dev/null || echo "end"
