#!/bin/bash -eu
. l3-2-ip/gen-bdrX

conf_interfaces_bdr_ospf () {
  cat <<END
!
interface Loopback0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.241 255.255.255.255
 ip ospf 41 area 0
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::241/128
 ipv6 ospf 41 area 0
 no shutdown
!
interface Null0
 no ip unreachables
!
interface GigabitEthernet0/0
 description Link to NREN
 ip address ${NREN_V4_SUBNET}.${NREN_V4_HOST} 255.255.255.252
 load-interval 30
 ipv6 address ${NREN_V6_SUBNET}:${CAMPUS}::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
!
interface GigabitEthernet0/1
 description Link to CAMPUS CORE
 ip address ${CAMPUS_CORE_V4_SUBNET}.1 255.255.255.240
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::1/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 ospf 41 area 0
 no shutdown
END
}
render_interfaces=conf_interfaces_bdr_ospf

conf_igp_bdr_ospf () {
  cat <<END
!
router ospf 41
 router-id ${CAMPUS_LOOP_V4_SUBNET}.241
 log-adjacency-changes
 passive-interface default
 no passive-interface GigabitEthernet0/1
 default-information originate
!
ipv6 router ospf 41
 router-id ${CAMPUS_LOOP_V4_SUBNET}.241
 log-adjacency-changes
 passive-interface default
 no passive-interface GigabitEthernet0/1
 default-information originate
END
}
render_igp=conf_igp_bdr_ospf

# Note: this originally had a pull-up route for v6:
#    ipv6 route ${CAMPUS_V6_BLOCK}::/48 Null0
# However, OSPFv3 doesn't work to core (IOSvL2 doesn't have OSPFv3).
# So for now, static route the whole block down to the core.
conf_static_bdr_ospf () {
  cat <<END
!
ip route 0.0.0.0 0.0.0.0 ${NREN_V4_SUBNET}.$((${NREN_V4_HOST} - 1))
ip route ${CAMPUS_CORE_V4_SUBNET}.0 255.255.255.0 Null0
ip route ${CAMPUS_V4_BLOCK}.0.0 255.255.0.0 Null0
!
ipv6 route ::/0 ${NREN_V6_SUBNET}:${CAMPUS}::0
ipv6 route ${CAMPUS_V6_BLOCK}::/48 ${CAMPUS_CORE_V6_SUBNET}::2
END
}
render_static=conf_static_bdr_ospf

return 2>/dev/null || render "$@"
