#!/bin/bash -eu
. l3-7-nms/gen-bdrX

conf_netflow_bdr_final () {
  cat <<END
!
flow exporter EXPORTER-1
  description Export to VM
  destination ${CAMPUS_CORE_V4_SUBNET}.130
  transport udp 9996
  template data timeout 60
!
flow monitor FLOW-MONITOR-V4
  exporter EXPORTER-1
  cache timeout active 300
  record netflow ipv4 original-input
!
flow monitor FLOW-MONITOR-V6
  exporter EXPORTER-1
  cache timeout active 300
  record netflow ipv6 original-input
END
}
render_netflow=conf_netflow_bdr_final

conf_interfaces_bdr_final () {
  cat <<END
!
interface Loopback0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.241 255.255.255.255
 ip ospf 41 area 0
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::241/128
 ipv6 ospf 41 area 0
 no shutdown
!
interface Null0
 no ip unreachables
!
interface GigabitEthernet0/0
 description Link to NREN
 ip address ${NREN_V4_SUBNET}.${NREN_V4_HOST} 255.255.255.252
 ip access-group from-nren in
 ip access-group to-nren out
 ip nat outside
 load-interval 30
 ipv6 address ${NREN_V6_SUBNET}:${CAMPUS}::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 traffic-filter from-nren-v6 in
 ipv6 traffic-filter to-nren-v6 out
 no shutdown
!
interface GigabitEthernet0/1
 description Link to CAMPUS CORE
 ip address ${CAMPUS_CORE_V4_SUBNET}.1 255.255.255.240
 ip flow monitor FLOW-MONITOR-V4 input
 ip flow monitor FLOW-MONITOR-V4 output
 ip nat inside
 ip ospf 41 area 0
 load-interval 30
 ipv6 flow monitor FLOW-MONITOR-V6 input
 ipv6 flow monitor FLOW-MONITOR-V6 output
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::1/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 ospf 41 area 0
 no shutdown
END
}
render_interfaces=conf_interfaces_bdr_final

return 2>/dev/null || render "$@"
