#!/bin/bash -eu
. l3-2-ip/gen-coreX

conf_interfaces_core_isis () {
  cat <<END
!
interface Loopback 0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.242 255.255.255.255
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::242/128
 no shutdown
!
interface GigabitEthernet0/0
 no switchport
 description CAMPUS CORE to BORDER
 ip address ${CAMPUS_CORE_V4_SUBNET}.2 255.255.255.240
 no ip redirects
 no ip proxy-arp
 ip router isis campus${CAMPUS}
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::2/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis campus${CAMPUS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
 no shutdown
END
  trunk GigabitEthernet0/1 10-12 "Trunk Link to dist1-b1.campus${CAMPUS}"
  trunk GigabitEthernet0/2 20-22 "Trunk Link to dist1-b2.campus${CAMPUS}"
cat <<END
!
interface GigabitEthernet0/3
 no switchport
 description Network Management and Monitoring
 ip address ${CAMPUS_SRVR_V4_SUBNET}.129 255.255.255.240
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_SRVR_V6_SUBNET}::1/64
 no shutdown
!
interface Vlan1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 no shutdown
!
interface Vlan11
 description Staff VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STAFF_SUBNET}.1 255.255.255.0
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STAFF_SUBNET}::1/64
 no shutdown
!
interface Vlan12
 description Student VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.1 255.255.255.0
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::1/64
 no shutdown
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 no shutdown
!
interface Vlan21
 description Staff VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STAFF_SUBNET}.1 255.255.255.0
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STAFF_SUBNET}::1/64
 no shutdown
!
interface Vlan22
 description Student VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.1 255.255.255.0
 no ip redirects
 no ip proxy-arp
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::1/64
 no shutdown
END
}
render_interfaces=conf_interfaces_core_isis

conf_igp_core_isis () {
  cat <<END
!
key chain isis-key
 key 1
   key-string cndlab123
!
router isis campus${CAMPUS}
 net 49.0001.000${CAMPUS}.0242.00
 is-type level-2-only
 authentication mode md5 level-2
 authentication key-chain isis-key level-2
 metric-style wide
 log-adjacency-changes all
 metric 100000
 passive-interface GigabitEthernet0/3
 passive-interface Loopback0
 passive-interface Vlan10
 passive-interface Vlan11
 passive-interface Vlan12
 passive-interface Vlan20
 passive-interface Vlan21
 passive-interface Vlan22
 !
 address-family ipv6
  multi-topology
  metric 100000
 exit-address-family
END
}
render_igp=conf_igp_core_isis

render_static=conf_null

return 2>/dev/null || render "$@"
