#!/bin/bash -eu
. common-A
preamble_iosv N
cat <<EOS
interface Loopback0
 description Loopback on A${GROUP}
 ip address 100.68.${GROUP}.4 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::4/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/0
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.21 255.255.255.254
 no ip redirects
 no ip proxy-arp
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:12::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet0/2
 description P2P Ethernet Link to Cust${GROUP}
 ip address 100.68.${GROUP}.34 255.255.255.254
 no ip redirects
 no ip proxy-arp
 duplex auto
 speed auto
 media-type rj45
 ipv6 address 2001:DB8:${GROUP}:31::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
interface GigabitEthernet0/3
 no ip address
 shutdown
 duplex auto
 speed auto
 media-type rj45
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
ipv6 ioam timestamp
!
EOS
postamble_iosv
