#!/bin/bash -eu
. common-B
preamble_iosv N
cat <<EOS
interface Loopback0
 description Loopback on B${GROUP}
 ip address 100.68.${GROUP}.1 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::1/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.17 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ipv6 address 2001:DB8:${GROUP}:10::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
ipv6 ioam timestamp
!
EOS
postamble_iosv
