#!/bin/bash -eu
CAMPUS=$2

. address-mappings

PRIORITY=0

cat <<EOM
hostname core1.campus${CAMPUS}
!
aaa new-model
aaa authentication login default local
aaa authentication enable default enable
!
no logging console
logging buffered 8192 debugging
ipv6 unicast-routing
ipv6 cef
no ip domain-lookup
ip domain name ws.nsrc.org
!
username cndlab secret lab-PW
enable secret lab-EN
service password-encryption
!
vtp mode transparent
!
vlan 10
 name MGMT1
vlan 11
 name STAFF1
vlan 12
 name STUDENT1
vlan 20
 name MGMT2
vlan 21
 name STAFF2
vlan 22
 name STUDENT2
!
interface Vlan 1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 load-interval 30
 no shut
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 load-interval 30
 no shut
!
spanning-tree vlan 10 priority ${PRIORITY}
spanning-tree vlan 11 priority ${PRIORITY}
spanning-tree vlan 12 priority ${PRIORITY}
spanning-tree vlan 20 priority ${PRIORITY}
spanning-tree vlan 21 priority ${PRIORITY}
spanning-tree vlan 22 priority ${PRIORITY}
!
interface GigabitEthernet0/1
 description Trunk Link to dist1-b1.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,10-12,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shutdown
!
interface GigabitEthernet0/2
 description Trunk Link to dist1-b2.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,20-22,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shutdown
!
line con 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line aux 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line vty 0 4
 exec-timeout 0 0
 transport preferred none
!
end
EOM
