#!/bin/bash -eu
CAMPUS=$2

. address-mappings

PRIORITY=0

cat <<EOM
hostname core1.campus${CAMPUS}
!
aaa new-model
aaa authentication login default local
aaa authentication enable default enable
!
no logging console
logging buffered 8192 debugging
ipv6 unicast-routing
ipv6 cef
no ip domain-lookup
ip domain name ws.nsrc.org
!
username cndlab secret lab-PW
enable secret lab-EN
service password-encryption
!
vtp mode transparent
!
vlan 10
 name MGMT1
vlan 11
 name STAFF1
vlan 12
 name STUDENT1
vlan 20
 name MGMT2
vlan 21
 name STAFF2
vlan 22
 name STUDENT2
!
interface Loopback 0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.242 255.255.255.255
 ip ospf 41 area 0
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::242/128
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan 1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 load-interval 30
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 ip access-group to-mgmt out
 ipv6 traffic-filter to-mgmt-v6 out
 no shut
!
interface Vlan11
 description Staff VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STAFF_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD1_V6_STAFF_SUBNET}::1/64
 load-interval 30
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 no shut
!
interface Vlan12
 description Student VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::1/64
 load-interval 30
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 no shut
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 load-interval 30
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 ip access-group to-mgmt out
 ipv6 traffic-filter to-mgmt-v6 out
 no shut
!
interface Vlan21
 description Staff VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STAFF_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD2_V6_STAFF_SUBNET}::1/64
 load-interval 30
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 no shut
!
interface Vlan22
 description Student VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.1 255.255.255.0
 ipv6 address ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::1/64
 load-interval 30
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 no shut
!
spanning-tree vlan 10 priority ${PRIORITY}
spanning-tree vlan 11 priority ${PRIORITY}
spanning-tree vlan 12 priority ${PRIORITY}
spanning-tree vlan 20 priority ${PRIORITY}
spanning-tree vlan 21 priority ${PRIORITY}
spanning-tree vlan 22 priority ${PRIORITY}
!
interface GigabitEthernet0/0
 no switchport
 description CAMPUS CORE to BORDER
 ip address ${CAMPUS_CORE_V4_SUBNET}.2 255.255.255.240
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::2/64
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 load-interval 30
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress
 no shutdown
!
interface GigabitEthernet0/1
 description Trunk Link to dist1-b1.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,10-12,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shutdown
!
interface GigabitEthernet0/2
 description Trunk Link to dist1-b2.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,20-22,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shutdown
!
interface GigabitEthernet0/3
 no switchport
 description Network Management and Monitoring
 ip address ${CAMPUS_SRVR_V4_SUBNET}.129 255.255.255.240
 ipv6 address ${CAMPUS_SRVR_V6_SUBNET}::1/64
 ip ospf 41 area 0
 ipv6 ospf 41 area 0
 load-interval 30
 no shutdown
!
router ospf 41
 router-id ${CAMPUS_LOOP_V4_SUBNET}.242
 log-adjacency-changes
 passive-interface default
 no passive-interface GigabitEthernet0/0
!
ipv6 router ospf 41
 router-id ${CAMPUS_LOOP_V4_SUBNET}.242
 log-adjacency-changes
 passive-interface default
 no passive-interface GigabitEthernet0/0
!
router bgp ${CAMPUS}0
 no bgp default ipv4-unicast
 bgp deterministic-med
 bgp router-id ${CAMPUS_LOOP_V4_SUBNET}.242
!
 address-family ipv4
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.241 remote-as ${CAMPUS}0
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.241 update-source loopback 0
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.241 description iBGP with Border Router
  neighbor ${CAMPUS_LOOP_V4_SUBNET}.241 activate
  network ${CAMPUS_CORE_V4_SUBNET}.0 mask 255.255.255.0
  network ${CAMPUS_V4_BLOCK}.0.0 mask 255.255.0.0
  distance bgp 200 200 200
!
 address-family ipv6
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::241 remote-as ${CAMPUS}0
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::241 update-source loopback0
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::241 description iBGP with Border Router
  neighbor ${CAMPUS_LOOP_V6_SUBNET}::241 activate
  network ${CAMPUS_V6_BLOCK}::/48
  distance bgp 200 200 200
!
ip route ${CAMPUS_CORE_V4_SUBNET}.0 255.255.255.0 Null0
ip route ${CAMPUS_V4_BLOCK}.0.0 255.255.0.0 Null0
ipv6 route ${CAMPUS_V6_BLOCK}::/48 Null0
!
ip access-list extended to-mgmt
 permit ip ${CAMPUS_SRVR_V4_SUBNET}.128 0.0.0.15 any
 deny   ip any any
!
ipv6 access-list to-mgmt-v6
 permit ipv6 ${CAMPUS_SRVR_V6_SUBNET}::/64 any
 deny ipv6 any any
!
line con 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line aux 0
 exec-timeout 0 0
 transport preferred none
 stopbits 1
line vty 0 4
 exec-timeout 0 0
 transport preferred none
!
end
EOM
