#!/bin/bash -eu
. "10-securing-bgp/$(basename "$0")"
. setup-iosv
. setup-sec
cat <<EOS
key chain as${AS}-key
 key 1
  key-string 7 0706325C42081B
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface Loopback0
 description Loopback on T${GROUP}
 ip address 100.68.${GROUP}.5 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::5/128
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.23 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ip router isis as${AS}
 ipv6 address 2001:DB8:${GROUP}:13::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
 no shutdown
!
router isis as${AS}
 net 49.0001.000${GROUP}.0005.00
 is-type level-2-only
 authentication mode md5 level-2
 authentication key-chain as${AS}-key level-2
 metric-style wide
 set-overload-bit on-startup wait-for-bgp
 log-adjacency-changes all
 metric 100000
 passive-interface Loopback0
 !
 address-family ipv6
  multi-topology
  set-overload-bit on-startup wait-for-bgp
  metric 100000
 exit-address-family
!
router bgp ${AS}
 bgp log-neighbor-changes
 bgp deterministic-med
 no bgp default ipv4-unicast
 neighbor ibgp-rr peer-group
 neighbor ibgp-rr remote-as ${AS}
 neighbor ibgp-rr description iBGP with RR
 neighbor ibgp-rr password 7 072D067C42081B
 neighbor ibgp-rr update-source Loopback0
 neighbor ibgpv6-rr peer-group
 neighbor ibgpv6-rr remote-as ${AS}
 neighbor ibgpv6-rr description iBGP with RR
 neighbor ibgpv6-rr password 7 15302C3C082B29
 neighbor ibgpv6-rr update-source Loopback0
 neighbor 2001:DB8:${GROUP}::2 peer-group ibgpv6-rr
 neighbor 2001:DB8:${GROUP}::2 description iBGP with Core
 neighbor 100.68.${GROUP}.2 peer-group ibgp-rr
 neighbor 100.68.${GROUP}.2 description iBGP with Core
 !
 address-family ipv4
  redistribute static route-map black-hole-trigger
  neighbor ibgp-rr send-community
  neighbor 100.68.${GROUP}.2 activate
  distance bgp 200 200 200
 exit-address-family
 !
 address-family ipv6
  distance bgp 200 200 200
  redistribute static route-map black-hole-triggerv6
  neighbor ibgpv6-rr send-community
  neighbor 2001:DB8:${GROUP}::2 activate
 exit-address-family
!
ip bgp-community new-format
ip community-list standard aggregate permit ${AS}:1000
ip community-list standard subnets permit ${AS}:1001
ip community-list standard customer-pi permit ${AS}:1005
ip community-list standard private-peer permit ${AS}:1100
ip community-list standard bilateral-peer permit ${AS}:1200
ip community-list standard RS-peer permit ${AS}:1300
!
ip route 8.8.8.8 255.255.255.255 Null0 tag 66
ip route 192.0.2.1 255.255.255.255 Null0
!
ipv6 route 100::1/128 Null0
ipv6 route 2001:4860:4860::8888/128 Null0 tag 66
!
route-map black-hole-trigger permit 10
 description Blackhole route conditions
 match tag 66
 set local-preference 1000
 set origin igp
 set community no-export
 set ip next-hop 192.0.2.1
!
route-map black-hole-triggerv6 permit 10
 description Blackhole route conditions
 match tag 66
 set local-preference 1000
 set origin igp
 set community no-export
 set ipv6 next-hop 100::1
!
EOS
return 2>/dev/null || echo "end"
