#!/bin/bash -eu
CUST_AS="$(( $1+135532 ))"
. "14-rpki/$(basename "$0")"
cat <<EOS
router bgp ${CUST_AS}
 address-family ipv4
  network 61.45.$(( GROUP+247 )).0 mask 255.255.255.0
 exit-address-family
!
ip route 61.45.$(( GROUP+247 )).0 255.255.255.0 Null0
!
ip prefix-list Cust${GROUP}-out permit 61.45.$(( GROUP+247 )).0/24
!
EOS
return 2>/dev/null || echo "end"
