#!/bin/bash -eu
. common-A
preamble_iosv
cat <<EOS
interface Loopback0
 description Loopback on A${GROUP}
 ip address 100.68.${GROUP}.4 255.255.255.255
 ipv6 address 2001:DB8:${GROUP}::4/128
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/1
 description P2P Ethernet Link to C${GROUP}
 ip address 100.68.${GROUP}.21 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ip router isis as${AS}
 ipv6 address 2001:DB8:${GROUP}:12::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
!
interface GigabitEthernet0/2
 description P2P Ethernet Link to Cust${GROUP}
 ip address 100.68.${GROUP}.34 255.255.255.254
 no ip redirects
 no ip proxy-arp
 ipv6 address 2001:DB8:${GROUP}:31::/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
!
router isis as${AS}
 net 49.0001.000${GROUP}.0004.00
 is-type level-2-only
 authentication mode md5 level-2
 authentication key-chain as${AS}-key level-2
 metric-style wide
 set-overload-bit on-startup wait-for-bgp
 log-adjacency-changes all
 metric 100000
 passive-interface Loopback0
 !
 address-family ipv6
  multi-topology
  set-overload-bit on-startup wait-for-bgp
  metric 100000
 exit-address-family
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
ipv6 ioam timestamp
!
EOS
postamble_iosv
