#!/bin/bash -eu
. "08-ixp-policy/$(basename "$0")"
cat <<EOS
router bgp ${AS}
 address-family ipv4
  network 100.68.${GROUP}.64 mask 255.255.255.192 route-map set-subnet-community
 exit-address-family
!
 address-family ipv6
  network 2001:DB8:${GROUP}:4000::/52 route-map set-subnet-community
 exit-address-family
!
ip bgp-community new-format
ip community-list standard aggregate permit ${AS}:1000
ip community-list standard subnets permit ${AS}:1001
ip community-list standard customer-pi permit ${AS}:1005
ip community-list standard private-peer permit ${AS}:1100
ip community-list standard bilateral-peer permit ${AS}:1200
ip community-list standard RS-peer permit ${AS}:1300
!
route-map set-subnet-community permit 5
 description Set community on Customer subnet
 set community ${AS}:1001
!
EOS
return 2>/dev/null || echo "end"
