#!/bin/bash -eu
. "08-ixp-policy/$(basename "$0")"
cat <<EOS
router bgp ${AS}
 address-family ipv4
  no neighbor ${PEER_REMOTE_V4} prefix-list AS${PEER_AS}-block in
  no neighbor ${PEER_REMOTE_V4} prefix-list AS${AS}-block out
  neighbor ${PEER_REMOTE_V4} route-map private-peer-out out
  no neighbor ${IXP_V4IXP}.254 prefix-list IXP-RS in
  no neighbor ${IXP_V4IXP}.254 prefix-list AS${AS}-block out
  neighbor ${IXP_V4IXP}.254 route-map IXP-RS-out out
 exit-address-family
 !
 address-family ipv6
  no neighbor ${PEER_REMOTE_V6} prefix-list AS${PEER_AS}-v6block in
  no neighbor ${PEER_REMOTE_V6} prefix-list AS${AS}-v6block out
  neighbor ${PEER_REMOTE_V6} route-map private-peerv6-in in
  neighbor ${PEER_REMOTE_V6} route-map private-peer-out out
  no neighbor ${IXP_V6BLOCK}:1::FE prefix-list IXP-v6RS in
  no neighbor ${IXP_V6BLOCK}:1::FE prefix-list AS${AS}-v6block out
  neighbor ${IXP_V6BLOCK}:1::FE route-map IXP-RSv6-in in
  neighbor ${IXP_V6BLOCK}:1::FE route-map IXP-RS-out out
 exit-address-family
!
ip bgp-community new-format
ip community-list standard aggregate permit ${AS}:1000
ip community-list standard subnets permit ${AS}:1001
ip community-list standard customer-pi permit ${AS}:1005
ip community-list standard private-peer permit ${AS}:1100
ip community-list standard bilateral-peer permit ${AS}:1200
ip community-list standard RS-peer permit ${AS}:1300
!
no ip prefix-list AS${AS}-block
!
no ipv6 prefix-list AS${AS}-v6block
!
route-map private-peer-out permit 5
 match community aggregate customer-pi
!
route-map IXP-RSv6-in permit 5
 description Local pref for IXP RS Peers
 match ipv6 address prefix-list IXP-v6RS
 set local-preference 150
 set community ${AS}:1300
!
route-map private-peerv6-in permit 5
 description Local pref for Private Peer
 match ipv6 address prefix-list AS${PEER_AS}-v6block
 set local-preference 200
 set community ${AS}:1100
!
route-map IXP-RS-out permit 5
 match community aggregate customer-pi
!
route-map IXP-RS-in permit 5
 description Local pref for IXP RS Peers
 match ip address prefix-list IXP-RS
 set local-preference 150
 set community ${AS}:1300
!
route-map private-peer-in permit 5
 description Local pref for Private Peer
 match ip address prefix-list AS${PEER_AS}-block
 set local-preference 200
 set community ${AS}:1100
!
EOS
return 2>/dev/null || echo "end"
