#!/bin/bash -eu
. "01-setup/$(basename "$0")"
cat <<EOS
key chain as${AS}-key
 key 1
  key-string 7 0706325C42081B
!
interface GigabitEthernet1
 ip router isis as${AS}
 ipv6 router isis as${AS}
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
!
router isis as${AS}
 net 49.0001.000${GROUP}.0001.00
 is-type level-2-only
 authentication mode md5 level-2
 authentication key-chain as${AS}-key level-2
 metric-style wide
 set-overload-bit on-startup wait-for-bgp
 log-adjacency-changes all
 metric 100000
 passive-interface Loopback0
 !
 address-family ipv6
  multi-topology
  set-overload-bit on-startup wait-for-bgp
  metric 100000
 exit-address-family
!
EOS
return 2>/dev/null || echo "end"
