#!/bin/bash -eu
. common-dist

PRIORITY=12288

conf_vlans_dist_vlan () {
  cat <<END
!
vtp mode off
!
vlan ${BUILDING}0
 name MGMT${BUILDING}
vlan ${BUILDING}1
 name STAFF${BUILDING}
vlan ${BUILDING}2
 name STUDENT${BUILDING}
END
}
render_vlans=conf_vlans_dist_vlan

conf_stp_dist_vlan () {
  cat <<END
!
spanning-tree vlan ${BUILDING}0 priority ${PRIORITY}
spanning-tree vlan ${BUILDING}1 priority ${PRIORITY}
spanning-tree vlan ${BUILDING}2 priority ${PRIORITY}
END
}
render_stp=conf_stp_dist_vlan

conf_interfaces_dist_l2final () {
  cat <<END
!
interface Vlan 1
 shutdown
!
interface Vlan${BUILDING}0
 description Management VLAN Building ${BUILDING}
 ip address ${IPV4_ADDRESS} 255.255.255.0
 ipv6 address ${IPV6_ADDRESS}/64
 load-interval 30
 no shut
!
interface Port-channel1
 description LAG to Edge Switch 1
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shut
!
interface GigabitEthernet0/0
 description Trunk Link to core1.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shut
!
interface GigabitEthernet1/0
 description Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 channel-group 1 mode on
 load-interval 30
 no shut
!
interface GigabitEthernet1/1
 description Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 channel-group 1 mode on
 load-interval 30
 no shut
!
interface GigabitEthernet2/0
 description Trunk Link to edge2-b${BUILDING}.campus${CAMPUS}
 switchport trunk allowed vlan 1,2,${BUILDING}0-${BUILDING}2,1002-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 load-interval 30
 no shut
END
}
render_interfaces=conf_interfaces_dist_l2final

render_static=conf_static_dist_edge

return 2>/dev/null || render_routed "$@"
