#!/bin/bash -eu
. common-core

PRIORITY=0

conf_vlans_core_default () {
  cat <<END
!
vtp mode off
!
vlan 10
 name MGMT1
vlan 11
 name STAFF1
vlan 12
 name STUDENT1
vlan 20
 name MGMT2
vlan 21
 name STAFF2
vlan 22
 name STUDENT2
END
}
render_vlans=conf_vlans_core_default

conf_stp_core_default () {
  cat <<END
!
spanning-tree mode mst
spanning-tree mst 0 priority ${PRIORITY}
END
}
render_stp=conf_stp_core_default

conf_interfaces_core_default () {
  cat <<END
!
interface Loopback0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.242 255.255.255.255
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::242/128
 no shutdown
!
interface Null0
 no ip unreachables
 no ipv6 unreachables
!
interface GigabitEthernet0/0
 no switchport
 description CAMPUS CORE to BORDER
 ip address ${CAMPUS_CORE_V4_SUBNET}.2 255.255.255.240
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::2/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
END
  trunk GigabitEthernet0/1 10-12 "Trunk Link to dist1-b1.campus${CAMPUS}"
  trunk GigabitEthernet0/2 20-22 "Trunk Link to dist1-b2.campus${CAMPUS}"
cat <<END
!
interface GigabitEthernet0/3
 no switchport
 description Network Management and Monitoring
 ip address ${CAMPUS_SRVR_V4_SUBNET}.129 255.255.255.240
 load-interval 30
 ipv6 address ${CAMPUS_SRVR_V6_SUBNET}::1/64
 no shutdown
!
interface Vlan1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 no shutdown
!
interface Vlan11
 description Staff VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STAFF_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STAFF_SUBNET}::1/64
 no shutdown
!
interface Vlan12
 description Student VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::1/64
 no shutdown
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 no shutdown
!
interface Vlan21
 description Staff VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STAFF_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STAFF_SUBNET}::1/64
 no shutdown
!
interface Vlan22
 description Student VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.1 255.255.255.0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::1/64
 no shutdown
!
END
}
render_interfaces=conf_interfaces_core_default

conf_static_core_default () {
  cat <<END
!
ip route 0.0.0.0 0.0.0.0 ${CAMPUS_CORE_V4_SUBNET}.1
ip route ${CAMPUS_CORE_V4_SUBNET}.0 255.255.255.0 Null0
ip route ${CAMPUS_LOOP_V4_SUBNET}.241 255.255.255.255 ${CAMPUS_CORE_V4_SUBNET}.1
ip route ${CAMPUS_V4_BLOCK}.0.0 255.255.0.0 Null0
!
ipv6 route ::/0 ${CAMPUS_CORE_V6_SUBNET}::1
ipv6 route ${CAMPUS_V6_BLOCK}::/48 Null0
ipv6 route ${CAMPUS_LOOP_V6_SUBNET}::241/128 ${CAMPUS_CORE_V6_SUBNET}::1
END
}
render_static=conf_static_core_default

return 2>/dev/null || render "$@"
