#!/bin/bash -eu
. common-dist

PRIORITY=12288

conf_vlans_dist_vlan () {
  cat <<END
!
vtp mode off
!
vlan ${BUILDING}0
 name MGMT${BUILDING}
vlan ${BUILDING}1
 name STAFF${BUILDING}
vlan ${BUILDING}2
 name STUDENT${BUILDING}
END
}
render_vlans=conf_vlans_dist_vlan

conf_stp_dist_vlan () {
  cat <<END
!
spanning-tree mode mst
spanning-tree mst 0 priority ${PRIORITY}
END
}
render_stp=conf_stp_dist_vlan

conf_interfaces_dist_l2final () {
  trunk Port-channel1 ${BUILDING}0-${BUILDING}2 "Aggregate Link to edge1-b${BUILDING}.campus${CAMPUS}"
  trunk GigabitEthernet0/0 ${BUILDING}0-${BUILDING}2 "Trunk Link to core1.campus${CAMPUS}"
  trunk GigabitEthernet0/1 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}"
  echo " channel-group 1 mode active"
  trunk GigabitEthernet0/2 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge1-b${BUILDING}.campus${CAMPUS}"
  echo " channel-group 1 mode active"
  trunk GigabitEthernet0/3 ${BUILDING}0-${BUILDING}2 "Trunk Link to edge2-b${BUILDING}.campus${CAMPUS}"
  cat <<END
!
interface Vlan 1
 shutdown
!
interface Vlan${BUILDING}0
 description Management VLAN Building ${BUILDING}
 ip address ${IPV4_ADDRESS} 255.255.255.0
 load-interval 30
 ipv6 address ${IPV6_ADDRESS}/64
 no shutdown
END
}
render_interfaces=conf_interfaces_dist_l2final

render_static=conf_static_dist_edge

return 2>/dev/null || render_routed "$@"
