#!/bin/bash -eu
. l3-4-nat/gen-bdrX

conf_interfaces_bdr_filter () {
  cat <<END
!
interface Loopback0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.241 255.255.255.255
 ip ospf 41 area 0
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::241/128
 ipv6 ospf 41 area 0
 no shutdown
!
interface Null0
 no ip unreachables
!
interface GigabitEthernet0/0
 description Link to NREN
 ip address ${NREN_V4_SUBNET}.${NREN_V4_HOST} 255.255.255.252
 ip access-group from-nren in
 ip access-group to-nren out
 ip nat outside
 load-interval 30
 ipv6 address ${NREN_V6_SUBNET}:${CAMPUS}::1/127
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 traffic-filter from-nren-v6 in
 ipv6 traffic-filter to-nren-v6 out
 no shutdown
!
interface GigabitEthernet0/1
 description Link to CAMPUS CORE
 ip address ${CAMPUS_CORE_V4_SUBNET}.1 255.255.255.240
 ip nat inside
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::1/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 ospf 41 area 0
 no shutdown
!
ip telnet source-interface Loopback0
END
}
render_interfaces=conf_interfaces_bdr_filter

conf_acl_bdr_filter () {
  conf_acl_bdr_nat
  cat <<END
!
ip access-list extended from-nren
 deny   ip ${CAMPUS_CORE_V4_SUBNET}.0 0.0.0.255 any
 permit ip any any
ip access-list extended to-nren
 remark Permit NREN point link subnet
 permit ip ${NREN_V4_SUBNET}.${NREN_V4_NET} 0.0.0.3 any
 remark Permit Campus ${CAMPUS} public IPv4 address block
 permit ip ${CAMPUS_CORE_V4_SUBNET}.0 0.0.0.255 any
 remark Deny any other sources
 deny   ip any any
!
ipv6 access-list from-nren-v6
 deny ipv6 ${CAMPUS_V6_BLOCK}::/48 any
 permit ipv6 any any
!
ipv6 access-list to-nren-v6
 remark Permit NREN point to point link subnet
 permit ipv6 ${NREN_V6_SUBNET}:${CAMPUS}::/127 any
 remark Permit Campus ${CAMPUS} public IPv6 address block
 permit ipv6 ${CAMPUS_V6_BLOCK}::/48 any
 remark Deny any other sources
 deny ipv6 any any
END
}
render_acl=conf_acl_bdr_filter

render_tail=conf_tail_management

return 2>/dev/null || render "$@"
