#!/bin/bash -eu
. l3-4-nat/gen-coreX

conf_interfaces_core_filter () {
  cat <<END
!
interface Loopback 0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.242 255.255.255.255
 ip ospf 41 area 0
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::242/128
 ipv6 ospf 41 area 0
 no shutdown
!
interface GigabitEthernet0/0
 no switchport
 description CAMPUS CORE to BORDER
 ip address ${CAMPUS_CORE_V4_SUBNET}.2 255.255.255.240
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::2/64
 ipv6 ospf 41 area 0
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 no shutdown
END
  trunk GigabitEthernet0/1 10-12 "Trunk Link to dist1-b1.campus${CAMPUS}"
  trunk GigabitEthernet0/2 20-22 "Trunk Link to dist1-b2.campus${CAMPUS}"
cat <<END
!
interface GigabitEthernet0/3
 no switchport
 description Network Management and Monitoring
 ip address ${CAMPUS_SRVR_V4_SUBNET}.129 255.255.255.240
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_SRVR_V6_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 ip access-group to-mgmt out
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 ipv6 traffic-filter to-mgmt-v6 out
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan11
 description Staff VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STAFF_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STAFF_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan12
 description Student VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 ip access-group to-mgmt out
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 ipv6 traffic-filter to-mgmt-v6 out
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan21
 description Staff VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STAFF_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STAFF_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
!
interface Vlan22
 description Student VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.1 255.255.255.0
 ip ospf 41 area 0
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::1/64
 ipv6 ospf 41 area 0
 no shutdown
END
}
render_interfaces=conf_interfaces_core_filter

conf_acl_core_filter () {
  cat <<END
!
ip access-list extended to-mgmt
 permit ip ${CAMPUS_SRVR_V4_SUBNET}.128 0.0.0.15 any
 deny   ip any any
!
ipv6 access-list to-mgmt-v6
 permit ipv6 ${CAMPUS_SRVR_V6_SUBNET}::/64 any
 deny ipv6 any any
END
}
render_acl=conf_acl_core_filter

return 2>/dev/null || render "$@"
