#!/bin/bash -eu
. l3-4-nat/gen-coreX

conf_interfaces_core_filter () {
  cat <<END
!
interface Loopback 0
 description Loopback
 ip address ${CAMPUS_LOOP_V4_SUBNET}.242 255.255.255.255
 ipv6 address ${CAMPUS_LOOP_V6_SUBNET}::242/128
 no shutdown
!
interface GigabitEthernet0/0
 no switchport
 description CAMPUS CORE to BORDER
 ip address ${CAMPUS_CORE_V4_SUBNET}.2 255.255.255.240
 ip router isis
 load-interval 30
 ipv6 address ${CAMPUS_CORE_V6_SUBNET}::2/64
 ipv6 nd prefix default no-advertise
 ipv6 nd ra suppress all
 ipv6 router isis
 isis network point-to-point
 isis metric 2
 isis ipv6 metric 2
 no shutdown
END
  trunk GigabitEthernet0/1 10-12 "Trunk Link to dist1-b1.campus${CAMPUS}"
  trunk GigabitEthernet0/2 20-22 "Trunk Link to dist1-b2.campus${CAMPUS}"
cat <<END
!
interface GigabitEthernet0/3
 no switchport
 description Network Management and Monitoring
 ip address ${CAMPUS_SRVR_V4_SUBNET}.129 255.255.255.240
 ip verify unicast source reachable-via rx allow-self-ping
 load-interval 30
 ipv6 address ${CAMPUS_SRVR_V6_SUBNET}::1/64
 ipv6 verify unicast source reachable-via rx
 no shutdown
!
interface Vlan1
 shutdown
!
interface Vlan10
 description Management VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_MGMT_SUBNET}.1 255.255.255.0
 ip verify unicast source reachable-via rx allow-self-ping
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_MGMT_SUBNET}::1/64
 ipv6 verify unicast source reachable-via rx
 no shutdown
!
interface Vlan11
 description Staff VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STAFF_SUBNET}.1 255.255.255.0
 ip verify unicast source reachable-via rx allow-self-ping
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STAFF_SUBNET}::1/64
 ipv6 verify unicast source reachable-via rx
 no shutdown
!
interface Vlan12
 description Student VLAN Building 1
 ip address ${CAMPUS_BLD1_V4_STUDENT_SUBNET}.1 255.255.255.0
 ip verify unicast source reachable-via rx allow-self-ping
 load-interval 30
 ipv6 address ${CAMPUS_BLD1_V6_STUDENT_SUBNET}::1/64
 ipv6 verify unicast source reachable-via rx
 no shutdown
!
interface Vlan20
 description Management VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_MGMT_SUBNET}.1 255.255.255.0
 ip verify unicast source reachable-via rx allow-self-ping
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_MGMT_SUBNET}::1/64
 ipv6 verify unicast source reachable-via rx
 no shutdown
!
interface Vlan21
 description Staff VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STAFF_SUBNET}.1 255.255.255.0
 ip verify unicast source reachable-via rx allow-self-ping
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STAFF_SUBNET}::1/64
 ipv6 verify unicast source reachable-via rx
 no shutdown
!
interface Vlan22
 description Student VLAN Building 2
 ip address ${CAMPUS_BLD2_V4_STUDENT_SUBNET}.1 255.255.255.0
 ip verify unicast source reachable-via rx allow-self-ping
 load-interval 30
 ipv6 address ${CAMPUS_BLD2_V6_STUDENT_SUBNET}::1/64
 ipv6 verify unicast source reachable-via rx
 no shutdown
!
ip telnet source-interface Loopback0
END
}
render_interfaces=conf_interfaces_core_filter

render_tail=conf_tail_management

return 2>/dev/null || render "$@"
