#!/bin/bash -eu
. l2-2-ip/gen-coreX
PRIORITY=0

conf_vlans_core_stp () {
  cat <<END
!
vtp mode off
END
}
render_vlans=conf_vlans_core_stp

conf_stp_core_stp () {
cat <<END
!
spanning-tree vlan 1 priority ${PRIORITY}
END
}
render_stp=conf_stp_core_stp

return 2>/dev/null || render "$@"
